/**
 * Load + parse the cartographic substrate TopoJSON (Lane Carto, spec-113 §7).
 *
 * `public/geo/counties.topojson`/`states.topojson` are generated by
 * `tools/build_geo_assets.mjs` from TIGER 2024 county shapefiles — see
 * `public/geo/README.md` for provenance. This module owns fetch+cache+decode; it never
 * mutates the underlying geometry (Constitution: the spatial substrate is immutable).
 */

import type { FeatureCollection, MultiPolygon, Polygon } from "geojson";
import { feature } from "topojson-client";
import type { GeometryCollection, Topology } from "topojson-specification";

/** Properties carried by every county feature — GEOID/NAME/STATEFP only (§7 task 1a). */
export interface CountyProperties {
  GEOID: string;
  NAME: string;
  STATEFP: string;
}

/** Properties carried by every state-dissolve feature. */
export interface StateProperties {
  STATEFP: string;
}

export type CountyTopology = Topology<{ counties: GeometryCollection<CountyProperties> }>;
export type StateTopology = Topology<{ states: GeometryCollection<StateProperties> }>;

export type CountyFeatureCollection = FeatureCollection<Polygon | MultiPolygon, CountyProperties>;
export type StateFeatureCollection = FeatureCollection<Polygon | MultiPolygon, StateProperties>;

const COUNTY_TOPOLOGY_URL = "/geo/counties.topojson";
const STATE_TOPOLOGY_URL = "/geo/states.topojson";

let cachedCountyTopology: CountyTopology | null = null;
let cachedCountyTopologyPromise: Promise<CountyTopology> | null = null;
let cachedStateTopology: StateTopology | null = null;
let cachedStateTopologyPromise: Promise<StateTopology> | null = null;

/**
 * Fetch + cache `public/geo/counties.topojson`. Concurrent callers before the first
 * resolution share one in-flight request; subsequent calls return the cached parse
 * synchronously wrapped in a resolved promise.
 */
export async function loadCountyTopology(): Promise<CountyTopology> {
  if (cachedCountyTopology) {
    return cachedCountyTopology;
  }
  if (!cachedCountyTopologyPromise) {
    cachedCountyTopologyPromise = fetchTopology<CountyTopology>(COUNTY_TOPOLOGY_URL).then(
      (topo) => {
        cachedCountyTopology = topo;
        return topo;
      },
    );
  }
  return cachedCountyTopologyPromise;
}

/** Fetch + cache `public/geo/states.topojson`. Same caching contract as `loadCountyTopology`. */
export async function loadStateTopology(): Promise<StateTopology> {
  if (cachedStateTopology) {
    return cachedStateTopology;
  }
  if (!cachedStateTopologyPromise) {
    cachedStateTopologyPromise = fetchTopology<StateTopology>(STATE_TOPOLOGY_URL).then((topo) => {
      cachedStateTopology = topo;
      return topo;
    });
  }
  return cachedStateTopologyPromise;
}

async function fetchTopology<T>(url: string): Promise<T> {
  const res = await fetch(url);
  if (!res.ok) {
    throw new Error(`Failed to load ${url}: ${res.status} ${res.statusText}`);
  }
  return (await res.json()) as T;
}

/** Extract the county `GeometryCollection` as a plain GeoJSON `FeatureCollection`. */
export function countyFeatures(topo: CountyTopology): CountyFeatureCollection {
  return feature(topo, topo.objects.counties) as CountyFeatureCollection;
}

/** Extract the state `GeometryCollection` as a plain GeoJSON `FeatureCollection`. */
export function stateFeatures(topo: StateTopology): StateFeatureCollection {
  return feature(topo, topo.objects.states) as StateFeatureCollection;
}

/** Test-only: reset the module-level fetch caches between test cases. */
export function resetGeoTopologyCache(): void {
  cachedCountyTopology = null;
  cachedCountyTopologyPromise = null;
  cachedStateTopology = null;
  cachedStateTopologyPromise = null;
}
