---

backup_user: "{{ server_user }}"
backup_group: "{{ backup_user }}"

backup_script_path: /usr/local/bin/backup-postgres.sh
backup_tmp_dir: /tmp

backup_daily_minute: "0"
backup_daily_hour: "3"
backup_weekly_minute: "30"
backup_weekly_hour: "3"
backup_weekly_weekday: "0"

rclone_remote_name: r2
r2_backup_bucket: babylon-backups
