"""Behavioral contract for Program 24 P7 — the KSBC aesthetic pass.

Two things this unit changed that ``tests/unit/render/test_design_bible_parity.py``
cannot see (it only imports ``babylon.tui.theme``, never boots a live app): the
shell must actually *apply* the ``ksbc`` theme at mount (not just register a Theme
object nobody activates), and the rails/panes/HUD/action-bar plates promoted from
:mod:`babylon.tui.shell.app_shell` must each carry the DESIGN_BIBLE §9b "title tab
breaks the border" label — a smoke check, not a pixel check (the SVG snapshot
goldens already regenerated by this unit cover the pixels).
"""

from __future__ import annotations

import pytest

from babylon.tui.app import _COPY_HINT, ArchiveApp
from babylon.tui.theme import CRIMSON, FIELD, GOLD, GREEN_DARK, PANEL, ROYAL

pytestmark = pytest.mark.unit


class TestKsbcThemeIsActuallyApplied:
    @pytest.mark.asyncio
    async def test_the_booted_shell_activates_ksbc_not_just_registers_it(self) -> None:
        app = ArchiveApp()
        async with app.run_test():
            assert app.theme == "ksbc"

    @pytest.mark.asyncio
    async def test_the_active_theme_colors_match_theme_pys_named_constants(self) -> None:
        """Guards against a future ``register_theme(KSBC)`` call that registers the
        right object but never flips ``app.theme`` — a green
        ``test_design_bible_parity`` gate over a theme nobody's actually seeing."""
        app = ArchiveApp()
        async with app.run_test():
            active = app.current_theme
            assert active.primary == CRIMSON
            assert active.accent == GOLD
            assert active.secondary == ROYAL
            assert active.success == GREEN_DARK
            assert active.error == CRIMSON
            assert active.background == FIELD
            assert active.panel == PANEL


class TestShellChromeCarriesItsTitleTab:
    """DESIGN_BIBLE §9b: "Title tab breaks the border: panel titles render as a
    label interrupting the top border line." The four domain panes + the HUD
    sub-strip had no chrome of their own before Program 24 P7, so they each got one.

    Unit "selection-unwrap" (shell-interconnect) extends this to the three rails:
    their own Rich-rendered content used to self-title via an inner ``Panel``
    (chronicle's per-tick bulletins, the watchlist's pin-count panel, the verb
    plate's org/tick panel) — that Panel is gone now (a bare, selectable ``Text``
    replaced it, so ``Widget.get_selection`` can extract it), so the SAME title
    moved to the Static's own CSS ``border_title`` instead, exactly like the four
    panes, plus a permanent ``border_subtitle`` copy-affordance hint neither the
    panes nor the pre-unit rails ever carried.
    """

    @pytest.mark.asyncio
    async def test_every_new_chrome_plate_carries_its_title_tab(self) -> None:
        app = ArchiveApp()
        async with app.run_test():
            expected = {
                "#dashboard": "DASHBOARD",
                "#dashboard-hud": "HUD",
                "#map": "MAP",
                "#wiki": "WIKI",
                "#topology": "TOPOLOGY",
            }
            for selector, title in expected.items():
                widget = app.query_one(selector)
                assert widget.border_title == title, (
                    f"{selector}: expected border_title {title!r}, got {widget.border_title!r}"
                )

    @pytest.mark.asyncio
    async def test_rails_and_action_bar_now_carry_their_own_title_tab(self) -> None:
        """Since their inner Panel is gone (unit "selection-unwrap"), the rails/
        action-bar each get a real ``border_title`` of their own — never ``None``
        — mirroring the four domain panes above, at the same boot-time seam
        (``ArchiveApp._apply_shell_chrome_titles``)."""
        app = ArchiveApp()
        async with app.run_test():
            expected = {
                "#chronicle-rail": "CHRONICLE",
                "#watchlist-rail": "Watchlist (0 pinned)",
                "#action-bar": "ACTION BAR — no verb plate wired yet",
            }
            for selector, title in expected.items():
                widget = app.query_one(selector)
                assert widget.border_title == title, (
                    f"{selector}: expected border_title {title!r}, got {widget.border_title!r}"
                )

    @pytest.mark.asyncio
    async def test_rails_and_action_bar_carry_the_permanent_copy_hint_subtitle(self) -> None:
        """The three un-paneled rails carry the same static
        :data:`~babylon.tui.app._COPY_HINT` ``border_subtitle`` — surfacing the
        already-live but undiscoverable ``ctrl+c``/``super+c`` copy binding now
        that mouse-drag selection on these rails actually extracts real text."""
        app = ArchiveApp()
        async with app.run_test():
            for selector in ("#chronicle-rail", "#watchlist-rail", "#action-bar"):
                assert app.query_one(selector).border_subtitle == _COPY_HINT
