"""Behavioral contract for Program 24 P7 — the KSBC aesthetic pass.

Two things this unit changed that ``tests/unit/render/test_design_bible_parity.py``
cannot see (it only imports ``babylon.tui.theme``, never boots a live app): the
shell must actually *apply* the ``ksbc`` theme at mount (not just register a Theme
object nobody activates), and the rails/panes/HUD/action-bar plates promoted from
:mod:`babylon.tui.shell.app_shell` must each carry the DESIGN_BIBLE §9b "title tab
breaks the border" label — a smoke check, not a pixel check (the SVG snapshot
goldens already regenerated by this unit cover the pixels).
"""

from __future__ import annotations

import pytest

from babylon.tui.app import ArchiveApp
from babylon.tui.theme import CRIMSON, FIELD, GOLD, GREEN_DARK, PANEL, ROYAL

pytestmark = pytest.mark.unit


class TestKsbcThemeIsActuallyApplied:
    @pytest.mark.asyncio
    async def test_the_booted_shell_activates_ksbc_not_just_registers_it(self) -> None:
        app = ArchiveApp()
        async with app.run_test():
            assert app.theme == "ksbc"

    @pytest.mark.asyncio
    async def test_the_active_theme_colors_match_theme_pys_named_constants(self) -> None:
        """Guards against a future ``register_theme(KSBC)`` call that registers the
        right object but never flips ``app.theme`` — a green
        ``test_design_bible_parity`` gate over a theme nobody's actually seeing."""
        app = ArchiveApp()
        async with app.run_test():
            active = app.current_theme
            assert active.primary == CRIMSON
            assert active.accent == GOLD
            assert active.secondary == ROYAL
            assert active.success == GREEN_DARK
            assert active.error == CRIMSON
            assert active.background == FIELD
            assert active.panel == PANEL


class TestShellChromeCarriesItsTitleTab:
    """DESIGN_BIBLE §9b: "Title tab breaks the border: panel titles render as a
    label interrupting the top border line." The four domain panes + the HUD
    sub-strip had no chrome of their own before this pass, so they each get one.
    The rails/action-bar deliberately do NOT — their own Rich-rendered content
    already carries a crimson-Panel + gold title (chronicle's per-tick bulletins,
    the watchlist's pin-count panel, the verb plate's org/tick panel), so boxing
    the rail widget too would double-frame that content inside an already-narrow
    24-column rail."""

    @pytest.mark.asyncio
    async def test_every_new_chrome_plate_carries_its_title_tab(self) -> None:
        app = ArchiveApp()
        async with app.run_test():
            expected = {
                "#dashboard": "DASHBOARD",
                "#dashboard-hud": "HUD",
                "#map": "MAP",
                "#wiki": "WIKI",
                "#topology": "TOPOLOGY",
            }
            for selector, title in expected.items():
                widget = app.query_one(selector)
                assert widget.border_title == title, (
                    f"{selector}: expected border_title {title!r}, got {widget.border_title!r}"
                )

    @pytest.mark.asyncio
    async def test_rails_and_action_bar_are_not_double_framed(self) -> None:
        """The rails/action-bar keep their pre-P7 partial separator border
        (crimson, one edge) — no outer ``border_title``, since their own
        Rich-rendered content already self-titles when populated."""
        app = ArchiveApp()
        async with app.run_test():
            for selector in ("#chronicle-rail", "#watchlist-rail", "#action-bar"):
                assert app.query_one(selector).border_title is None
