// synopticon-data.jsx — Mock data for The Synopticon (State surveillance dashboard)
//
// Naming convention: every entity is a code, not a name. The state does not see
// people. It sees nodes. Names are stripped before storage; aliases are signals
// generated by the system itself ("ROSARY-7" = first clustered match in liturgical
// vocabulary bucket, instance 7).

// ============================================================================
// META — what the state thinks it knows
// ============================================================================
const META = {
  tick: 247,
  operator: "AURELIUS-7",
  classification: "TS//SCI//SAP-LAVENDER//STATE-EYES-ONLY",
  sub_classification: "REL TO STATE.DOMESTIC, STATE.IMPERIAL",
  caveat: "ORCON · NOFORN · NO-ARCHIVE-RETENTION",
  population_observed: 18472330,
  legible_nodes: 1284,
  coverage_pct: 0.78,      // 78% of true world state visible
  signal_loss_pct: 0.22,
  flagged: 89,            // risk > monitor threshold
  on_suppress: 31,        // risk > suppress
  on_kill_list: 7,        // risk > eliminate
  threads_total: 320,     // repression resources
  threads_used: 187,
  threads_available: 133,
  cde_policy: 12,         // current collateral damage tolerance (max civilians)
  decoy_strikes_t_minus_30: 3,
  legitimacy: 0.42,       // state legitimacy (you're hemorrhaging it)
  agitation: 0.67,        // your blowback (their problem)
};

// ============================================================================
// RISK THRESHOLDS — Lavender V1
// ============================================================================
const THRESHOLDS = {
  monitor:   0.4,
  suppress:  0.7,
  eliminate: 0.9,
};

// ============================================================================
// CHANNEL COLORS — one per risk contribution feature
// ============================================================================
const FEATURE_COLORS = {
  centrality:  "var(--cadre)",       // royal blue — courier / connector
  association: "var(--rent)",        // purple — guilt by neighbor
  velocity:    "var(--heat)",        // orange — spending anomaly
  geo:         "var(--laser)",       // red — presence in heat zones
};

// ============================================================================
// DOSSIERS — 24 entries, ordered by descending risk_score
// Risk arithmetic: total = clamp(centrality + association + velocity + geo, 0..1)
// ============================================================================
const D = (id, alias, status, c, a, v, g, m, s, k, cde, terr, neigh, decoy, first, last, dossier_age, history) => {
  const total = Math.min(1.0, c + a + v + g);
  return {
    id, alias, status,
    risk_score: +total.toFixed(2),
    contributions: { centrality: c, association: a, velocity: v, geo: g },
    pol_vector: { movement: m, spending: s, communication: k },
    collateral_estimate: cde,
    territory: terr,
    neighbors: neigh,
    decoy_probability: decoy,
    first_seen: first,
    last_observed: last,
    dossier_age,
    history,
  };
};

const DOSSIERS = [
  // === ELIMINATE (risk > 0.9) ===
  D("ENT-7741-A", "VECTOR/ROSARY-7", "TARGET",
    0.40, 0.18, 0.22, 0.13,  0.82, 0.71, 0.94,  8,
    "T-04 · NORTHWEST DETROIT", 14, 0.03, "T-189", "T-247", 58,
    [
      { t: 247, sev: "high",   tag: "RENDEZVOUS",      note: "Geo-cluster w/ ENT-3318, ENT-9912 at 41.7N -83.5W" },
      { t: 246, sev: "med",    tag: "BURST_COMMS",     note: "26 short signals, encrypted, 04:11-04:23" },
      { t: 244, sev: "med",    tag: "INCOME_GAP",      note: "Spending = 2.4× declared income (prior 90 ticks)" },
      { t: 240, sev: "high",   tag: "HEAT_ZONE",       note: "Sustained presence in TERR-04 (insurgent index 0.81)" },
      { t: 232, sev: "low",    tag: "TOPOLOGY",        note: "Betweenness centrality crosses 0.85 percentile" },
    ]),
  D("ENT-3318-B", "MASON/CRADLE-2", "TARGET",
    0.40, 0.20, 0.18, 0.14,  0.66, 0.82, 0.78,  3,
    "T-04 · NORTHWEST DETROIT", 11, 0.04, "T-201", "T-247", 46,
    [
      { t: 247, sev: "high",   tag: "RENDEZVOUS",      note: "Co-located w/ ENT-7741 (high-risk anchor)" },
      { t: 245, sev: "med",    tag: "ASSET_TRANSFER",  note: "Resource flow to ENT-9912 (×0.4 daily spend)" },
      { t: 242, sev: "low",    tag: "GEO_DRIFT",       note: "Migration pattern leaves declared residence by 11 km" },
      { t: 238, sev: "med",    tag: "ASSOCIATION",     note: "Neighbor-risk-avg rises to 0.71" },
    ]),
  D("ENT-9912-C", "LOOM/PILGRIM-3", "TARGET",
    0.32, 0.20, 0.26, 0.13,  0.91, 0.44, 0.88,  6,
    "T-07 · LAKE CITY SOUTH", 9, 0.06, "T-167", "T-247", 80,
    [
      { t: 247, sev: "med",    tag: "BURST_COMMS",     note: "Long signal to ENT-7741 · 41s (anomaly)" },
      { t: 244, sev: "high",   tag: "ROUTE_CHANGE",    note: "Commute pattern deviates by 5σ for 4 consec ticks" },
      { t: 240, sev: "med",    tag: "SPEND_SPIKE",     note: "Cash-equivalent draw 4.1× baseline" },
    ]),
  // === SUPPRESS (risk 0.7-0.9) ===
  D("ENT-2204-D", "QUILL/ANCHOR-1", "SUSPECT",
    0.28, 0.16, 0.24, 0.16,  0.62, 0.55, 0.81,  19,
    "T-11 · WESTSIDE CHICAGO", 22, 0.02, "T-145", "T-246", 102,
    [
      { t: 246, sev: "med",    tag: "HEAT_ZONE",       note: "Two-tick presence in TERR-11 (heat 0.74)" },
      { t: 243, sev: "low",    tag: "ASSOCIATION",     note: "3 of 6 frequent contacts now flagged" },
      { t: 238, sev: "med",    tag: "INCOME_GAP",      note: "Velocity anomaly persists (×1.9)" },
    ]),
  D("ENT-5587-E", "FERRIC/SAW-4", "SUSPECT",
    0.24, 0.20, 0.20, 0.20,  0.71, 0.62, 0.66,  5,
    "T-04 · NORTHWEST DETROIT", 8, 0.41 /* HIGH decoy probability */, "T-220", "T-247", 27,
    [
      { t: 247, sev: "med",    tag: "HONEYPOT_FLAG",   note: "Signal entropy anomalously stable — possible decoy" },
      { t: 246, sev: "med",    tag: "RENDEZVOUS",      note: "Co-located w/ multiple high-risk nodes" },
      { t: 244, sev: "high",   tag: "ROUTE_CHANGE",    note: "Movement pattern unnaturally legible" },
    ]),
  D("ENT-4419-F", "OAK/HARNESS-9", "SUSPECT",
    0.36, 0.14, 0.18, 0.12,  0.55, 0.38, 0.92,  11,
    "T-22 · SOUTH BRONX", 17, 0.05, "T-178", "T-247", 69,
    [
      { t: 247, sev: "low",    tag: "BURST_COMMS",     note: "Spike in encrypted msg count (×3)" },
      { t: 243, sev: "med",    tag: "TOPOLOGY",        note: "Connector node — bridges 2 disjoint clusters" },
      { t: 234, sev: "low",    tag: "ASSOCIATION",     note: "2 of 9 contacts flagged" },
    ]),
  D("ENT-6630-G", "TIN/SPARROW-5", "SUSPECT",
    0.20, 0.22, 0.16, 0.18,  0.48, 0.51, 0.74,  31,
    "T-11 · WESTSIDE CHICAGO", 26, 0.01, "T-118", "T-247", 129,
    [
      { t: 247, sev: "low",    tag: "ASSOCIATION",     note: "Avg neighbor risk now 0.62" },
      { t: 245, sev: "med",    tag: "HEAT_ZONE",       note: "Crossed TERR-11 boundary 3× last tick" },
      { t: 240, sev: "low",    tag: "INCOME_GAP",      note: "Spending ×1.4 — mild anomaly" },
    ]),
  D("ENT-1102-H", "STAR/COG-3", "SUSPECT",
    0.18, 0.18, 0.18, 0.18,  0.61, 0.59, 0.58,  7,
    "T-07 · LAKE CITY SOUTH", 13, 0.07, "T-202", "T-247", 45,
    [
      { t: 246, sev: "low",    tag: "BURST_COMMS",     note: "Pattern matches courier signature" },
      { t: 244, sev: "low",    tag: "ROUTE_CHANGE",    note: "Repeated dwell at unflagged location" },
    ]),
  // === MONITOR (0.4-0.7) ===
  D("ENT-8821-J", "WIRE/GLASS-1", "SUSPECT",
    0.16, 0.18, 0.16, 0.12,  0.42, 0.44, 0.66,  4,
    "T-15 · LONG BEACH", 12, 0.08, "T-188", "T-246", 59,
    [
      { t: 246, sev: "low",    tag: "ASSOCIATION",     note: "Cluster-id matches active enclave" },
      { t: 240, sev: "low",    tag: "GEO_DRIFT",       note: "Border-zone presence rising" },
    ]),
  D("ENT-3309-K", "ROPE/EMBER-8", "SUSPECT",
    0.12, 0.16, 0.18, 0.14,  0.34, 0.48, 0.51,  9,
    "T-22 · SOUTH BRONX", 18, 0.04, "T-195", "T-247", 52,
    [
      { t: 245, sev: "low",    tag: "INCOME_GAP",      note: "Spending ×1.6 of declared" },
    ]),
  D("ENT-7780-L", "FUSE/CORDAGE-2", "SUSPECT",
    0.12, 0.14, 0.16, 0.16,  0.39, 0.41, 0.48,  21,
    "T-04 · NORTHWEST DETROIT", 19, 0.06, "T-204", "T-247", 43,
    [
      { t: 244, sev: "low",    tag: "HEAT_ZONE",       note: "TERR-04 presence twice last tick" },
    ]),
  D("ENT-2916-M", "VINE/MORTAR-6", "SUSPECT",
    0.18, 0.10, 0.14, 0.10,  0.36, 0.27, 0.62,  3,
    "T-30 · OAKLAND HILLS", 11, 0.09, "T-181", "T-243", 62,
    [
      { t: 243, sev: "low",    tag: "BURST_COMMS",     note: "Mild signal anomaly" },
    ]),
  D("ENT-1153-N", "PETAL/IRON-9", "SUSPECT",
    0.08, 0.18, 0.10, 0.12,  0.31, 0.38, 0.45,  16,
    "T-15 · LONG BEACH", 24, 0.03, "T-210", "T-247", 37,
    [
      { t: 240, sev: "low",    tag: "ASSOCIATION",     note: "5 of 14 neighbors flagged" },
    ]),
  D("ENT-9072-P", "BARLEY/AXLE-4", "SUSPECT",
    0.10, 0.12, 0.12, 0.10,  0.28, 0.31, 0.51,  6,
    "T-07 · LAKE CITY SOUTH", 10, 0.05, "T-219", "T-247", 28,
    [
      { t: 238, sev: "low",    tag: "GEO_DRIFT",       note: "Slow drift toward heat zone" },
    ]),
  // === UNKNOWN ===
  D("ENT-4451-Q", "MOSS/THORN-2", "UNKNOWN",
    0.06, 0.10, 0.08, 0.12,  0.18, 0.22, 0.34,  14,
    "T-22 · SOUTH BRONX", 9, 0.03, "T-201", "T-247", 46,
    [
      { t: 235, sev: "low",    tag: "BACKGROUND",      note: "Below monitor threshold; passive accumulation" },
    ]),
  D("ENT-2828-R", "CINDER/NAIL-3", "UNKNOWN",
    0.04, 0.12, 0.06, 0.10,  0.14, 0.18, 0.31,  19,
    "T-30 · OAKLAND HILLS", 7, 0.02, "T-211", "T-246", 36,
    []),
  D("ENT-8009-S", "RIVET/PSALM-1", "UNKNOWN",
    0.06, 0.06, 0.08, 0.10,  0.16, 0.21, 0.26,  11,
    "T-15 · LONG BEACH", 6, 0.02, "T-228", "T-247", 19,
    []),
  // === ELIMINATED — historical, for context ===
  D("ENT-5510-T", "CHALK/WIRE-6", "ELIMINATED",
    0.38, 0.22, 0.22, 0.18,  0.0,  0.0,  0.0,  14,
    "T-04 · NORTHWEST DETROIT", 0, 0.0, "T-156", "T-228 ⨯", 72,
    [
      { t: 228, sev: "high",   tag: "STRIKE_EXEC",     note: "Engaged. CDE 14 / policy 12. POST-STRIKE: agitation +0.31." },
      { t: 227, sev: "high",   tag: "QUEUED",          note: "Promoted to Gospel index 1" },
    ]),
  D("ENT-1820-U", "ASH/HARP-5", "ELIMINATED",
    0.34, 0.20, 0.18, 0.20,  0.0,  0.0,  0.0,  6,
    "T-11 · WESTSIDE CHICAGO", 0, 0.78 /* WAS A DECOY */, "T-198", "T-222 ⨯", 24,
    [
      { t: 222, sev: "high",   tag: "BLOWBACK",        note: "POST-STRIKE: target classified DECOY. Legitimacy -0.30, agitation +0.50." },
      { t: 221, sev: "high",   tag: "STRIKE_EXEC",     note: "Engaged. CDE 6 within policy. Threat-class CONFIRMED at strike-time." },
    ]),
];

// ============================================================================
// SPARROW NETWORK — what the state sees of YOUR organization
// (positions are pre-laid out; r reflects centrality; risk-color filled)
// ============================================================================
// Cluster positions: NW Detroit cluster (top-left), Westside Chicago (top-right),
// Lake City (bottom-left), South Bronx (bottom-right), Long Beach (middle).
const NETWORK = {
  nodes: [
    // NW Detroit cluster — high-risk anchor
    { id: "n01", entity: "ENT-7741-A", x: 220, y: 160, c: 0.93, r: 0.93, s: "TARGET",     a: "ROSARY-7" },
    { id: "n02", entity: "ENT-3318-B", x: 290, y: 210, c: 0.78, r: 0.92, s: "TARGET",     a: "CRADLE-2" },
    { id: "n03", entity: "ENT-5587-E", x: 160, y: 230, c: 0.62, r: 0.84, s: "SUSPECT",    a: "SAW-4 ◆decoy" },
    { id: "n04", entity: "ENT-7780-L", x: 250, y: 280, c: 0.34, r: 0.58, s: "SUSPECT",    a: "CORDAGE-2" },
    { id: "n05", entity: "ENT-5510-T", x: 120, y: 175, c: 0.0,  r: 0.0,  s: "ELIMINATED", a: "WIRE-6 ⨯" },
    // Lake City
    { id: "n06", entity: "ENT-9912-C", x: 290, y: 460, c: 0.71, r: 0.91, s: "TARGET",     a: "PILGRIM-3" },
    { id: "n07", entity: "ENT-1102-H", x: 360, y: 530, c: 0.50, r: 0.72, s: "SUSPECT",    a: "COG-3" },
    { id: "n08", entity: "ENT-9072-P", x: 240, y: 540, c: 0.24, r: 0.44, s: "SUSPECT",    a: "AXLE-4" },
    // Chicago / Bronx (joined via Quill)
    { id: "n09", entity: "ENT-2204-D", x: 660, y: 200, c: 0.66, r: 0.84, s: "SUSPECT",    a: "ANCHOR-1" },
    { id: "n10", entity: "ENT-6630-G", x: 740, y: 270, c: 0.46, r: 0.76, s: "SUSPECT",    a: "SPARROW-5" },
    { id: "n11", entity: "ENT-1820-U", x: 590, y: 270, c: 0.0,  r: 0.0,  s: "ELIMINATED", a: "HARP-5 ⨯◆" },
    // South Bronx
    { id: "n12", entity: "ENT-4419-F", x: 740, y: 460, c: 0.58, r: 0.78, s: "SUSPECT",    a: "HARNESS-9" },
    { id: "n13", entity: "ENT-3309-K", x: 820, y: 520, c: 0.30, r: 0.60, s: "SUSPECT",    a: "EMBER-8" },
    { id: "n14", entity: "ENT-4451-Q", x: 670, y: 540, c: 0.18, r: 0.36, s: "UNKNOWN",    a: "THORN-2" },
    // Long Beach (bridge)
    { id: "n15", entity: "ENT-8821-J", x: 470, y: 360, c: 0.38, r: 0.62, s: "SUSPECT",    a: "GLASS-1" },
    { id: "n16", entity: "ENT-1153-N", x: 510, y: 460, c: 0.24, r: 0.48, s: "SUSPECT",    a: "IRON-9" },
    { id: "n17", entity: "ENT-8009-S", x: 430, y: 270, c: 0.14, r: 0.30, s: "UNKNOWN",    a: "PSALM-1" },
    // Oakland
    { id: "n18", entity: "ENT-2916-M", x: 460, y: 540, c: 0.24, r: 0.52, s: "SUSPECT",    a: "MORTAR-6" },
    { id: "n19", entity: "ENT-2828-R", x: 380, y: 200, c: 0.16, r: 0.32, s: "UNKNOWN",    a: "NAIL-3" },
    // ghost nodes — partial coverage (signal loss)
    { id: "g01", entity: "ENT-????-X", x: 360, y: 380, c: 0.10, r: null, s: "GHOST",      a: "???" },
    { id: "g02", entity: "ENT-????-Y", x: 580, y: 380, c: 0.10, r: null, s: "GHOST",      a: "???" },
  ],
  edges: [
    // NW Detroit internal
    ["n01","n02",0.9],["n01","n03",0.7],["n02","n04",0.6],["n01","n05",0.8],
    // Detroit -> Lake City (long bridge through PILGRIM)
    ["n01","n06",0.5],["n06","n07",0.7],["n06","n08",0.5],
    // Chicago cluster
    ["n09","n10",0.8],["n09","n11",0.6],["n10","n11",0.5],
    // Bronx cluster
    ["n12","n13",0.7],["n12","n14",0.5],["n13","n14",0.4],
    // bridges across — Long Beach as the connector (high betweenness)
    ["n09","n15",0.6],["n15","n12",0.6],["n15","n01",0.4],["n15","n06",0.4],
    ["n16","n15",0.5],["n16","n18",0.5],["n17","n01",0.3],["n17","n15",0.3],
    ["n19","n02",0.4],
    // ghost edges — what the state THINKS exists but only partially
    ["g01","n15",0.2],["g01","n06",0.2],["g02","n09",0.2],["g02","n12",0.2],
  ],
};

// ============================================================================
// GOSPEL QUEUE — sorted strike list (the "Kill List")
// ============================================================================
const GOSPEL = [
  { rank:1, entity:"ENT-7741-A", alias:"ROSARY-7",   risk:0.93, cde:8,  opp:0.74, status:"QUEUED",    eta:"T+0", threads:18, terr:"T-04", decoy:0.03 },
  { rank:2, entity:"ENT-3318-B", alias:"CRADLE-2",   risk:0.92, cde:3,  opp:0.81, status:"QUEUED",    eta:"T+0", threads:14, terr:"T-04", decoy:0.04 },
  { rank:3, entity:"ENT-9912-C", alias:"PILGRIM-3",  risk:0.91, cde:6,  opp:0.62, status:"QUEUED",    eta:"T+1", threads:16, terr:"T-07", decoy:0.06 },
  { rank:4, entity:"ENT-2204-D", alias:"ANCHOR-1",   risk:0.84, cde:19, opp:0.55, status:"CDE_HOLD",  eta:"—",   threads:0,  terr:"T-11", decoy:0.02 },
  { rank:5, entity:"ENT-5587-E", alias:"SAW-4",      risk:0.84, cde:5,  opp:0.78, status:"QUEUED",    eta:"T+1", threads:12, terr:"T-04", decoy:0.41 },
  { rank:6, entity:"ENT-4419-F", alias:"HARNESS-9",  risk:0.78, cde:11, opp:0.43, status:"QUEUED",    eta:"T+2", threads:11, terr:"T-22", decoy:0.05 },
  { rank:7, entity:"ENT-6630-G", alias:"SPARROW-5",  risk:0.76, cde:31, opp:0.31, status:"CDE_HOLD",  eta:"—",   threads:0,  terr:"T-11", decoy:0.01 },
  { rank:8, entity:"ENT-1102-H", alias:"COG-3",      risk:0.72, cde:7,  opp:0.49, status:"QUEUED",    eta:"T+2", threads:9,  terr:"T-07", decoy:0.07 },
  { rank:9, entity:"ENT-8821-J", alias:"GLASS-1",    risk:0.62, cde:4,  opp:0.38, status:"MONITOR",   eta:"—",   threads:0,  terr:"T-15", decoy:0.08 },
  { rank:10,entity:"ENT-3309-K", alias:"EMBER-8",    risk:0.60, cde:9,  opp:0.42, status:"MONITOR",   eta:"—",   threads:0,  terr:"T-22", decoy:0.04 },
  { rank:11,entity:"ENT-7780-L", alias:"CORDAGE-2",  risk:0.58, cde:21, opp:0.28, status:"CDE_HOLD",  eta:"—",   threads:0,  terr:"T-04", decoy:0.06 },
  { rank:12,entity:"ENT-2916-M", alias:"MORTAR-6",   risk:0.52, cde:3,  opp:0.36, status:"MONITOR",   eta:"—",   threads:0,  terr:"T-30", decoy:0.09 },
];

// ============================================================================
// DOCTRINE — the algorithm itself, rendered as a state document
// ============================================================================
const DOCTRINE = {
  lavender: {
    name: "LAVENDER-V1",
    classification: "TS//SAP-LAVENDER",
    purpose: "Score every legible entity. Each tick. Without exception.",
    inputs: ["LegibleGraph", "PatternOfLifeLog"],
    features: [
      {
        key: "centrality",
        label: "BETWEENNESS CENTRALITY",
        cap: 0.40,
        formula: "f₁ = 0.40 · normalize( BC(node, LegibleGraph) )",
        logic: "Couriers and bridge nodes carry information between cells. High betweenness = high operational value to the org. Therefore: high risk.",
        note: "The state does not distinguish a courier from a mother-in-law. Both bridge clusters.",
      },
      {
        key: "association",
        label: "NEIGHBOR-RISK AVERAGE",
        cap: 0.20,
        formula: "f₂ = 0.20 · mean( risk[neighbor] for neighbor in N(node) )",
        logic: "Guilt by topology. If your neighbors are flagged, you are flagged. Iterates each tick — contagion in the dossier space.",
        note: "Cleanly produces second-order targets without additional evidence collection.",
      },
      {
        key: "velocity",
        label: "VELOCITY ANOMALY",
        cap: 0.30,
        formula: "f₃ = 0.30 · clamp( log(spend/declared_income) , 0, 1 )",
        logic: "Spending exceeds declared income → illicit funding. Used as a proxy for material support to insurgency.",
        note: "Penalizes informal-economy survival, mutual aid, and remittance networks identically to illicit finance.",
      },
      {
        key: "geo",
        label: "GEO-SIGNATURE",
        cap: 0.20,
        formula: "f₄ = 0.20 · sum( heat[territory] · dwell[territory] )",
        logic: "Presence in 'heat zones' (territories with insurgency index > 0.5) adds risk proportional to dwell time.",
        note: "Lives in the wrong zip code → permanent baseline risk.",
      },
    ],
    composition: "RISK = clamp(f₁ + f₂ + f₃ + f₄, 0, 1)",
    thresholds: THRESHOLDS,
  },
  gospel: {
    name: "THE GOSPEL",
    classification: "TS//SAP-LAVENDER//STRIKE-AUTH",
    purpose: "Assign automated strike priority. Maintain throughput.",
    trigger: "After Lavender. Every tick.",
    sort: [
      { key: "PRIMARY",   label: "Risk score descending"            },
      { key: "SECONDARY", label: "Opportunity — low-defense terr."  },
      { key: "TIE-BREAK", label: "Lower CDE first (efficiency)"     },
    ],
    constraints: [
      { key: "BUDGET",   label: "Thread allocation (320 available)" },
      { key: "POLICY",   label: "CDE policy ceiling (currently 12)" },
      { key: "PR",       label: "Decoy probability advisory (informational only — not blocking)" },
    ],
    execution: [
      "Filter: queue items where CDE ≤ POLICY",
      "Allocate threads top-down until budget exhausted",
      "Engage. Compute Assess. Move on.",
    ],
    notes: [
      "The Gospel does not see motive. It sees position.",
      "The Gospel does not see the decoy. The decoy is, by definition, indistinguishable in the legible projection.",
      "Assess attributes any change in Agitation to the strike. Blowback is therefore mislabeled as efficacy.",
    ],
  },
};

// ============================================================================
// AGGREGATE STATS — risk distribution for the panopticon histogram
// ============================================================================
const RISK_HISTOGRAM = [
  // [bin_low, bin_high, count, bucket_label]
  [0.0, 0.1, 612, ""],
  [0.1, 0.2, 224, ""],
  [0.2, 0.3, 138, ""],
  [0.3, 0.4,  92, ""],
  [0.4, 0.5,  68, "MONITOR"],
  [0.5, 0.6,  54, ""],
  [0.6, 0.7,  41, ""],
  [0.7, 0.8,  26, "SUPPRESS"],
  [0.8, 0.9,  18, ""],
  [0.9, 1.0,   7, "ELIMINATE"],
];

// ============================================================================
// TIME SERIES — last 30 ticks (for the sparkline on the panopticon)
// ============================================================================
const TIMESERIES = {
  flagged: [62,64,67,71,69,72,76,78,75,79,82,80,84,82,86,88,87,84,82,80,79,82,84,86,85,88,87,89,89,89],
  on_kill: [ 2, 2, 3, 3, 3, 4, 4, 4, 5, 5, 5, 6, 6, 6, 7, 7, 6, 6, 6, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7],
  strikes: [ 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1],
  blowback:[ 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
};

// ============================================================================
// TERRITORIES — for heat zone lookup
// ============================================================================
const TERRITORIES = {
  "T-04": { name: "NORTHWEST DETROIT",  heat: 0.81, defense: 0.32, control: 0.41 },
  "T-07": { name: "LAKE CITY SOUTH",    heat: 0.74, defense: 0.28, control: 0.48 },
  "T-11": { name: "WESTSIDE CHICAGO",   heat: 0.62, defense: 0.51, control: 0.62 },
  "T-15": { name: "LONG BEACH",         heat: 0.44, defense: 0.39, control: 0.71 },
  "T-22": { name: "SOUTH BRONX",        heat: 0.58, defense: 0.36, control: 0.55 },
  "T-30": { name: "OAKLAND HILLS",      heat: 0.36, defense: 0.44, control: 0.74 },
};

// ============================================================================
// Export
// ============================================================================
window.SYN_DATA = {
  META, THRESHOLDS, FEATURE_COLORS,
  DOSSIERS, NETWORK, GOSPEL, DOCTRINE,
  RISK_HISTOGRAM, TIMESERIES, TERRITORIES,
};
