# Generated by Django 5.2.11 on 2026-03-04 01:49

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ActionResult",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("tick", models.IntegerField()),
                ("org_id", models.CharField(max_length=64)),
                ("action_type", models.CharField(max_length=32)),
                ("target_id", models.CharField(blank=True, max_length=64, null=True)),
                (
                    "target_community",
                    models.CharField(blank=True, max_length=32, null=True),
                ),
                ("initiative_score", models.FloatField()),
                ("action_cost", models.FloatField()),
                ("success", models.BooleanField()),
                ("consciousness_delta", models.FloatField(blank=True, null=True)),
                ("heat_delta", models.FloatField(blank=True, null=True)),
                ("details", models.JSONField(blank=True, null=True)),
            ],
            options={
                "db_table": "action_result",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="GameSession",
            fields=[
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
                ),
                ("player_id", models.IntegerField(blank=True, null=True)),
                ("scenario", models.CharField(max_length=64)),
                ("current_tick", models.IntegerField(default=0)),
                ("status", models.CharField(default="active", max_length=16)),
                ("config_json", models.JSONField(default=dict)),
                ("game_defines_json", models.JSONField(default=dict)),
                ("trace_level", models.CharField(default="NONE", max_length=8)),
                ("rng_seed", models.BigIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "game_session",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="PlayerAction",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("tick", models.IntegerField()),
                ("org_id", models.CharField(max_length=64)),
                ("verb", models.CharField(max_length=16)),
                ("action_type", models.CharField(blank=True, max_length=32, null=True)),
                ("target_id", models.CharField(blank=True, max_length=64, null=True)),
                (
                    "target_community",
                    models.CharField(blank=True, max_length=32, null=True),
                ),
                ("params_json", models.JSONField(blank=True, null=True)),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                ("resolved", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "game_turn",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="GameEventLog",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("game_create", "Game Created"),
                            ("game_pause", "Game Paused"),
                            ("game_resume", "Game Resumed"),
                            ("tick_resolve", "Tick Resolved"),
                            ("action_submit", "Action Submitted"),
                            ("engine_error", "Engine Error"),
                            ("auth_login", "User Login"),
                            ("auth_logout", "User Logout"),
                            ("auth_fail", "Login Failed"),
                        ],
                        db_index=True,
                        max_length=32,
                    ),
                ),
                ("session_id", models.UUIDField(blank=True, db_index=True, null=True)),
                ("user_id", models.IntegerField(blank=True, db_index=True, null=True)),
                ("tick", models.IntegerField(blank=True, null=True)),
                ("message", models.TextField()),
                ("details", models.JSONField(blank=True, null=True)),
                (
                    "correlation_id",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
            ],
            options={
                "db_table": "game_event_log",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(fields=["session_id", "tick"], name="idx_event_session_tick")
                ],
            },
        ),
    ]
