# Generated by Django 5.2.11 on 2026-07-08 15:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("game", "0011_communitysnapshot_economicsummary_edgesnapshot_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gameeventlog",
            name="category",
            field=models.CharField(
                choices=[
                    ("game_create", "Game Created"),
                    ("game_pause", "Game Paused"),
                    ("game_resume", "Game Resumed"),
                    ("game_recover", "Game Recovered"),
                    ("tick_resolve", "Tick Resolved"),
                    ("action_submit", "Action Submitted"),
                    ("engine_error", "Engine Error"),
                    ("auth_login", "User Login"),
                    ("auth_logout", "User Logout"),
                    ("auth_fail", "Login Failed"),
                ],
                db_index=True,
                max_length=32,
            ),
        ),
    ]
