# Generated by Django 5.2.16 on 2026-07-15 02:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("game", "0013_hexstate_attributes"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClassSnapshot",
            fields=[
                ("tick", models.IntegerField()),
                (
                    "class_id",
                    models.CharField(max_length=64, primary_key=True, serialize=False),
                ),
                ("role", models.CharField(max_length=32)),
                ("wealth", models.FloatField(null=True)),
                ("subsistence_threshold", models.FloatField(null=True)),
                ("population", models.IntegerField(null=True)),
                ("inequality", models.FloatField(null=True)),
                ("organization", models.FloatField(null=True)),
                ("repression_faced", models.FloatField(null=True)),
                ("class_consciousness", models.FloatField(null=True)),
                ("national_identity", models.FloatField(null=True)),
                ("agitation", models.FloatField(null=True)),
                ("p_acquiescence", models.FloatField(null=True)),
                ("p_revolution", models.FloatField(null=True)),
                ("active", models.BooleanField(default=True)),
                ("attributes", models.JSONField(default=dict)),
            ],
            options={
                "db_table": "class_snapshot",
                "managed": False,
            },
        ),
    ]
