# Generated by Django 5.2.16 on 2026-07-15 02:15
#
# Amended 2026-07-15 (heavy-tier triage): the unmanaged model below is a DB
# no-op, so a fresh Django-migrated database never got the class_snapshot
# TABLE — only the engine's `mise run db:bootstrap` created it, and the
# playwright-e2e job (the one heavy-tier job that migrates without the
# bootstrap) crashed on 0003's index pass. The RunPython here now ships the
# engine-owned DDL (table + its indexes) with the migration, mirroring how
# 0003 ships the other engine-owned spec-037 tables.

from django.db import migrations, models

from babylon.persistence.postgres_schema import (
    CLASS_SNAPSHOT_DDL,
    CLASS_SNAPSHOT_INDEXES_DDL,
)


def forwards(apps, schema_editor):  # type: ignore[no-untyped-def]
    if schema_editor.connection.vendor != "postgresql":
        return
    schema_editor.execute(CLASS_SNAPSHOT_DDL)
    for idx_ddl in CLASS_SNAPSHOT_INDEXES_DDL:
        schema_editor.execute(idx_ddl)


def backwards(apps, schema_editor):  # type: ignore[no-untyped-def]
    if schema_editor.connection.vendor != "postgresql":
        return
    schema_editor.execute("DROP TABLE IF EXISTS class_snapshot CASCADE;")


class Migration(migrations.Migration):
    dependencies = [
        ("game", "0013_hexstate_attributes"),
    ]

    operations = [
        migrations.RunPython(forwards, backwards),
        migrations.CreateModel(
            name="ClassSnapshot",
            fields=[
                ("tick", models.IntegerField()),
                (
                    "class_id",
                    models.CharField(max_length=64, primary_key=True, serialize=False),
                ),
                ("role", models.CharField(max_length=32)),
                ("wealth", models.FloatField(null=True)),
                ("subsistence_threshold", models.FloatField(null=True)),
                ("population", models.IntegerField(null=True)),
                ("inequality", models.FloatField(null=True)),
                ("organization", models.FloatField(null=True)),
                ("repression_faced", models.FloatField(null=True)),
                ("class_consciousness", models.FloatField(null=True)),
                ("national_identity", models.FloatField(null=True)),
                ("agitation", models.FloatField(null=True)),
                ("p_acquiescence", models.FloatField(null=True)),
                ("p_revolution", models.FloatField(null=True)),
                ("active", models.BooleanField(default=True)),
                ("attributes", models.JSONField(default=dict)),
            ],
            options={
                "db_table": "class_snapshot",
                "managed": False,
            },
        ),
    ]
