# Generated by Django 5.2.16 on 2026-07-15 07:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("game", "0014_classsnapshot"),
    ]

    operations = [
        migrations.CreateModel(
            name="NarrationRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tick", models.IntegerField()),
                ("beat_id", models.CharField(max_length=64)),
                (
                    "scope",
                    models.CharField(
                        choices=[
                            ("event", "Event"),
                            ("tick", "Tick"),
                            ("county", "County"),
                            ("endgame", "Endgame"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "subject_ref",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                ("headline", models.TextField()),
                ("body", models.TextField()),
                (
                    "register",
                    models.CharField(
                        choices=[("wire", "Wire"), ("analysis", "Analysis")],
                        max_length=16,
                    ),
                ),
                ("model_id", models.CharField(max_length=128)),
                ("prompt_version", models.CharField(max_length=32)),
                ("degraded", models.BooleanField(default=False)),
                ("error", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="narration_records",
                        to="game.gamesession",
                    ),
                ),
            ],
            options={
                "db_table": "narration_record",
                "ordering": ("tick", "beat_id"),
                "unique_together": {("session", "tick", "beat_id")},
            },
        ),
    ]
