version: 1
disable_existing_loggers: false
formatters:
  standard:
    format: '%(asctime)s [%(levelname)s] %(name)s: %(message)s'
  json:
    # Use custom JSONFormatter - no external dependencies
    class: babylon.utils.log.JSONFormatter

handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: standard
    stream: ext://sys.stdout
  file:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: json
    filename: 'logs/babylon.log'
    maxBytes: 10000000  # 10MB
    backupCount: 5
  error_file:
    class: logging.handlers.RotatingFileHandler
    level: ERROR
    formatter: json
    filename: 'logs/errors.log'
    maxBytes: 5000000  # 5MB
    backupCount: 10

loggers:
  '':
    level: DEBUG
    handlers: [console, file, error_file]
  # Suppress noisy third-party loggers
  chromadb:
    level: WARNING
  httpx:
    level: WARNING
  httpcore:
    level: WARNING
