"""Interest rate and burden computation.

Models the determination of interest rates from FRED data and computes
per-county interest burden. FR-003 guarantees that the effective interest
rate for industrial borrowers never exceeds the county profit rate.

Feature: 024-capital-volume-iii (US2, FR-002, FR-003)

See Also:
    :class:`InterestRateState`: National interest rate snapshot.
    :mod:`babylon.domain.economics.credit.data_sources`: FRED data protocols.
"""

from __future__ import annotations

from typing import Protocol

from babylon.domain.economics.credit.data_sources import InterestRateSource
from babylon.domain.economics.credit.types import InterestRateState
from babylon.domain.economics.tensor import NoDataSentinel


class InterestCalculator(Protocol):
    """Protocol for interest rate computation."""

    def compute_interest_rate_state(self, year: int) -> InterestRateState | NoDataSentinel:
        """Compute national interest rate state from FRED data.

        Args:
            year: Calendar year.

        Returns:
            InterestRateState if data available, NoDataSentinel otherwise.
        """
        ...

    def compute_county_interest_burden(
        self,
        national_rate: float,
        county_profit_rate: float,
        county_capital_stock: float,
    ) -> float:
        """Compute interest burden for a county.

        Args:
            national_rate: National effective interest rate.
            county_profit_rate: County-level profit rate.
            county_capital_stock: County-level capital stock.

        Returns:
            Interest burden (dollars).
        """
        ...


class DefaultInterestCalculator:
    """Interest rate computation from FRED data.

    FR-003: Effective rate for industrial borrowers is capped at
    the county profit rate. Capital cannot extract more in interest
    than the profit generated by industrial capital.
    """

    def __init__(self, rate_source: InterestRateSource) -> None:
        self._rate_source = rate_source

    def compute_interest_rate_state(self, year: int) -> InterestRateState | NoDataSentinel:
        """Compute national interest rate state from FRED data.

        Args:
            year: Calendar year.

        Returns:
            InterestRateState with FRED values, or NoDataSentinel
            with distinct reason string per missing field.
        """
        fed_funds = self._rate_source.get_federal_funds_rate(year)
        if fed_funds is None:
            return NoDataSentinel(
                fips="USA",
                year=year,
                reason=f"Federal funds rate unavailable for {year}",
            )

        treasury = self._rate_source.get_treasury_10y(year)
        if treasury is None:
            return NoDataSentinel(
                fips="USA",
                year=year,
                reason=f"10Y Treasury yield unavailable for {year}",
            )

        spread = self._rate_source.get_baa_spread(year)
        if spread is None:
            return NoDataSentinel(
                fips="USA",
                year=year,
                reason=f"Baa spread unavailable for {year}",
            )

        return InterestRateState(
            year=year,
            base_rate=fed_funds,
            treasury_10y=treasury,
            baa_spread=spread,
        )

    def compute_county_interest_burden(
        self,
        national_rate: float,
        county_profit_rate: float,
        county_capital_stock: float,
    ) -> float:
        """Compute interest burden for a county.

        FR-003: effective rate = min(national_rate, county_profit_rate).
        Interest-bearing capital cannot extract more than the profit
        generated by productive capital in the county.

        Args:
            national_rate: National effective interest rate.
            county_profit_rate: County-level profit rate.
            county_capital_stock: County-level capital stock.

        Returns:
            Interest burden = effective_rate * capital_stock.
        """
        effective = min(national_rate, county_profit_rate)
        return effective * county_capital_stock
