//! Rolling capacity is physical service, not a lifetime endowment or cash balance.
use super::*;

fn rolling(mut state: MaterialCircuitState) -> MaterialCircuitState {
    state.capacities.retain(|row| row.period == state.period);
    state
        .corridor_capacities
        .retain(|row| row.period == state.period);
    state.capacity_supply = CapacitySupply::Rolling(Box::new(RollingCapacitySupply {
        installed_processes: state
            .capacities
            .iter()
            .map(|row| InstalledProcessCapacity {
                process_id: row.process_id,
                site_id: row.site_id,
                batches_per_period: row.available_batches,
            })
            .collect(),
        shared: state
            .corridor_capacities
            .iter()
            .map(|row| SharedCapacitySupply {
                corridor_id: row.corridor_id,
                grams_per_period: row.available_grams,
            })
            .collect(),
        future_reservations: vec![],
    }));
    state
}

fn staffing() -> StaffingState {
    let pools = [(1, 1), (2, 2), (3, 1)]
        .into_iter()
        .map(|(owner, persons)| {
            let source = if owner == 3 {
                StaffingWorkSource::MerchantHandling(site(owner))
            } else {
                StaffingWorkSource::Production(process(owner))
            };
            let binding = StaffingPoolBinding::try_new(
                StaffingPoolId::from_bytes([owner; 32]),
                site(owner),
                hours(),
                persons,
                StaffingPolicy::one_period(4).unwrap(),
                vec![source],
            )
            .unwrap();
            StaffingPoolState::try_new(binding, persons, 0, persons * 4).unwrap()
        })
        .collect();
    StaffingState::try_new(1, pools).unwrap()
}

fn staffed_close(
    state: &MaterialCircuitState,
    people: &StaffingState,
) -> (MaterialCircuitTransition, StaffingState) {
    let closed = close_material_period(state).unwrap();
    let bindings = people
        .pools()
        .iter()
        .map(|pool| pool.binding().clone())
        .collect::<Vec<_>>();
    let requests = closed.staffing_requests(&bindings).unwrap();
    let staffing = advance_staffing(people, &requests).unwrap();
    let result = closed
        .finish_with_labor(staffing.next_labor().to_vec())
        .unwrap();
    (result, staffing.state().clone())
}

#[test]
fn staffed_recurring_eighty_periods_and_restart_preserve_goods_money_and_capacity() {
    let mut state = rolling(opening());
    state.inventory[0].quantity = 400; // Finite material resource, not regenerated by capacity.
    state.labor.retain(|row| row.period == 1);
    let mut people = staffing();
    let mut consumed = 0;
    let mut fork = None;
    for period in 1..=80 {
        if period == 52 {
            let bytes = encode_material_circuit_state(&state).unwrap();
            fork = Some((
                decode_material_circuit_state(&bytes).unwrap(),
                people.clone(),
            ));
        }
        let (closed, next_people) = staffed_close(&state, &people);
        if let Some((restart, restart_people)) = &mut fork {
            let (replayed, replayed_people) = staffed_close(restart, restart_people);
            assert_eq!(closed, replayed, "restart period {period}");
            assert_eq!(next_people, replayed_people);
            *restart = replayed.state;
            *restart_people = replayed_people;
        }
        consumed += closed.household_consumption[0].consumed_quantity;
        assert_eq!(
            economy(&closed.state)
                .book
                .total_cash_and_reserves()
                .unwrap(),
            money(24)
        );
        let physical = closed
            .state
            .inventory
            .iter()
            .map(|r| r.quantity)
            .sum::<u64>()
            + closed.state.freight.iter().map(|r| r.quantity).sum::<u64>()
            + economy(&closed.state)
                .recurring
                .as_ref()
                .unwrap()
                .household_stocks[0]
                .quantity;
        assert_eq!(physical + consumed, 416);
        assert_eq!(closed.state.capacities.len(), 2);
        assert_eq!(closed.state.corridor_capacities.len(), 3);
        assert!(closed
            .state
            .capacities
            .iter()
            .all(|r| r.period == period + 1));
        assert!(closed
            .state
            .corridor_capacities
            .iter()
            .all(|r| r.period == period + 1));
        assert_eq!(closed.state.labor.len(), 3);
        if period > 52 {
            assert_eq!(closed.household_consumption[0].consumed_quantity, 4);
            assert_eq!(output(&closed, 1), 4);
            assert_eq!(output(&closed, 2), 4);
        }
        people = next_people;
        state = closed.state;
    }
}

#[test]
fn finite_controls_do_not_extrapolate_missing_capacity() {
    let mut state = opening();
    state.capacities.retain(|row| row.period == 1);
    state.corridor_capacities.retain(|row| row.period == 1);
    let first = advance_material_circuit(&state).unwrap();
    assert!(first.state.capacities.is_empty());
    assert!(first.state.corridor_capacities.is_empty());
    assert!(first.state.production_commitments.is_empty());
    let second = advance_material_circuit(&first.state).unwrap();
    assert!(second.dispatches.is_empty());
    assert_eq!(second.household_demand[0].fulfilled_quantity, 0);
}

fn add_order(state: &mut MaterialCircuitState, buyer: u8, quantity: u64) {
    let id = OrderId::from_bytes([buyer; 32]);
    state.orders.push(OrderRow {
        order_id: id,
        access_mode: OrderAccessMode::CommoditySale,
        supplier_site_id: site(1),
        buyer_site_id: site(buyer),
        good_id: good(1),
        unit_id: units(),
        ordered: quantity,
        shipped: 0,
        delivered: 0,
        realized: 0,
        lost: 0,
    });
    state.backlog.push(BacklogRow {
        order_id: id,
        quantity,
    });
}

fn freight_opening() -> MaterialCircuitState {
    let mut state = opening();
    state.period = 50;
    state.accounting = CircuitAccounting::PhysicalControl;
    state.process_outputs.clear();
    state.input_coefficients.clear();
    state.labor_coefficients.clear();
    state.production_commitments.clear();
    state.capacities.clear();
    state.labor.clear();
    state.merchants.clear();
    state.handling_coefficients.clear();
    state.final_demand_principals.clear();
    state.inventory = vec![inventory(1, 1, 20)];
    state.site_logistics_nodes.push(SiteLogisticsNode {
        site_id: site(4),
        node_id: node(4),
    });
    state.supplier_routes = [2, 3, 4]
        .into_iter()
        .map(|buyer| SupplierRoute {
            supplier_site_id: site(1),
            buyer_site_id: site(buyer),
            good_id: good(1),
            unit_id: units(),
            route_id: route(buyer),
            transport_kind: SupplierTransport::Staged,
        })
        .collect();
    state.route_stages = [
        (2, 0, 1, 5, 1, 1_000_000),
        (2, 1, 5, 6, 1, 0),
        (2, 2, 6, 2, 1, 0),
        (3, 0, 1, 3, 1, 0),
        (4, 0, 1, 5, 1, 0),
        (4, 1, 5, 4, 1, 0),
    ]
    .into_iter()
    .map(
        |(id, stage_index, from, to, travel_periods, loss_ppm)| RouteStage {
            route_id: route(id),
            stage_index,
            from_node_id: node(from),
            to_node_id: node(to),
            travel_periods,
            loss_ppm,
        },
    )
    .collect();
    state.route_stage_capacities = [
        (2, 0, 1),
        (2, 1, 1),
        (2, 2, 2),
        (3, 0, 2),
        (4, 0, 3),
        (4, 1, 2),
    ]
    .into_iter()
    .map(|(r, stage_index, c)| RouteStageCapacity {
        route_id: route(r),
        stage_index,
        corridor_id: corridor(c),
    })
    .collect();
    state.corridor_capacities = [1, 2, 3]
        .into_iter()
        .map(|c| CorridorCapacity {
            corridor_id: corridor(c),
            period: 50,
            available_grams: 10,
        })
        .collect();
    add_order(&mut state, 2, 7);
    rolling(state)
}

#[test]
fn future_departures_remain_reserved_after_total_loss_and_checkpoint_restart() {
    let first = advance_material_circuit(&freight_opening()).unwrap();
    assert_eq!(first.dispatches[0].quantity, 7);
    let mut state = first.state;
    add_order(&mut state, 4, 8);
    let bytes = encode_material_circuit_state(&state).unwrap();
    let restarted = decode_material_circuit_state(&bytes).unwrap();
    let second = advance_material_circuit(&state).unwrap();
    assert_eq!(second, advance_material_circuit(&restarted).unwrap());
    assert_eq!(second.dispatches[0].quantity, 3);
    let mut state = second.state;
    assert_eq!(state.period, 52);
    assert_eq!(
        state
            .corridor_capacities
            .iter()
            .find(|r| r.corridor_id == corridor(2))
            .unwrap()
            .available_grams,
        0
    );
    add_order(&mut state, 3, 1);
    let third = advance_material_circuit(&state).unwrap();
    assert_eq!(second.losses.iter().map(|r| r.quantity).sum::<u64>(), 7);
    assert!(third.losses.is_empty());
    assert!(!third
        .state
        .freight
        .iter()
        .any(|r| r.order_id == OrderId::from_bytes([2; 32])));
    assert!(!third
        .dispatches
        .iter()
        .any(|r| r.order_id == OrderId::from_bytes([3; 32])));
    assert_eq!(
        third
            .state
            .inventory
            .iter()
            .map(|r| r.quantity)
            .sum::<u64>()
            + third.state.freight.iter().map(|r| r.quantity).sum::<u64>()
            + 7,
        20
    );
    // The second order's five still-unshipped units now book departure 53.
    assert_eq!(
        third
            .dispatches
            .iter()
            .find(|row| row.order_id == OrderId::from_bytes([4; 32]))
            .unwrap()
            .quantity,
        5
    );
    assert_eq!(
        third
            .state
            .corridor_capacities
            .iter()
            .find(|r| r.corridor_id == corridor(2))
            .unwrap()
            .available_grams,
        5
    );
}

#[test]
fn rolling_wire_refuses_obsolete_noncanonical_and_invalid_bookings() {
    let state = rolling(opening());
    let bytes = encode_material_circuit_state(&state).unwrap();
    assert_eq!(decode_material_circuit_state(&bytes).unwrap(), state);
    let version = MATERIAL_CIRCUIT_STATE_DOMAIN_BYTES.len() + 1;
    let mut obsolete = bytes.clone();
    obsolete[version..version + 2].copy_from_slice(&6_u16.to_be_bytes());
    assert_eq!(
        decode_material_circuit_state(&obsolete),
        Err(MaterialCircuitError::WireVersion)
    );
    let CapacitySupply::Rolling(rows) = &state.capacity_supply else {
        unreachable!()
    };
    let payload_len = 1 + 12 + rows.installed_processes.len() * 72 + rows.shared.len() * 40;
    let mode = bytes.len() - payload_len - 8; // Two empty service row counts follow capacity.
    let mut invalid = bytes.clone();
    invalid[mode] = 2;
    assert_eq!(
        decode_material_circuit_state(&invalid),
        Err(MaterialCircuitError::WireEnum)
    );
    let mut unordered = bytes.clone();
    unordered[mode + 5..mode + 5 + 144].rotate_left(72);
    assert_eq!(
        decode_material_circuit_state(&unordered),
        Err(MaterialCircuitError::WireNoncanonical)
    );
    for end in mode..bytes.len() {
        assert!(decode_material_circuit_state(&bytes[..end]).is_err());
    }
    let mut duplicate = state.clone();
    let CapacitySupply::Rolling(rows) = &mut duplicate.capacity_supply else {
        unreachable!()
    };
    rows.shared.push(rows.shared[0].clone());
    assert_eq!(
        encode_material_circuit_state(&duplicate),
        Err(MaterialCircuitError::DuplicateRow)
    );
    for (departure_period, c, reserved_grams) in [
        (49, 2, 1),
        (50, 2, 1),
        (53, 2, 1),
        (52, 3, 1),
        (52, 2, 0),
        (52, 2, 11),
    ] {
        let mut invalid = freight_opening();
        let CapacitySupply::Rolling(rows) = &mut invalid.capacity_supply else {
            unreachable!()
        };
        rows.future_reservations.push(FutureCapacityReservation {
            departure_period,
            corridor_id: corridor(c),
            reserved_grams,
        });
        assert_eq!(
            encode_material_circuit_state(&invalid),
            Err(MaterialCircuitError::CapacityInvariant)
        );
    }
    let mut excessive = state.clone();
    let CapacitySupply::Rolling(rows) = &mut excessive.capacity_supply else {
        unreachable!()
    };
    rows.shared = vec![rows.shared[0].clone(); MAX_MATERIAL_CIRCUIT_ROWS + 1];
    assert_eq!(
        encode_material_circuit_state(&excessive),
        Err(MaterialCircuitError::RowLimit)
    );
    let mut excessive = bytes.clone();
    excessive[mode + 1..mode + 5].copy_from_slice(
        &u32::try_from(MAX_MATERIAL_CIRCUIT_ROWS + 1)
            .unwrap()
            .to_be_bytes(),
    );
    assert_eq!(
        decode_material_circuit_state(&excessive),
        Err(MaterialCircuitError::WireLimit)
    );
}

#[test]
fn date_overflow_and_late_planning_failure_publish_no_capacity_or_money_changes() {
    let mut state = freight_opening();
    state.period = u64::MAX;
    for row in &mut state.corridor_capacities {
        row.period = state.period;
    }
    let before = encode_material_circuit_state(&state).unwrap();
    assert_eq!(
        advance_material_circuit(&state),
        Err(MaterialCircuitError::Arithmetic)
    );
    assert_eq!(encode_material_circuit_state(&state).unwrap(), before);

    let mut state = rolling(opening());
    recurring_mut(&mut state).production[0].output_buffer = u64::MAX;
    state.route_stages[0].to_node_id = node(9);
    state.route_stages.push(RouteStage {
        route_id: route(1),
        stage_index: 1,
        from_node_id: node(9),
        to_node_id: node(2),
        travel_periods: 1,
        loss_ppm: 0,
    });
    state.route_stage_capacities.push(RouteStageCapacity {
        route_id: route(1),
        stage_index: 1,
        corridor_id: corridor(1),
    });
    let before = encode_material_circuit_state(&state).unwrap();
    // Payroll, retail settlement and a newly reserved future departure precede
    // overflow of dispatched_quantity + output_buffer in production planning.
    assert_eq!(
        advance_material_circuit(&state),
        Err(MaterialCircuitError::Arithmetic)
    );
    assert_eq!(encode_material_circuit_state(&state).unwrap(), before);
}
