"""Consciousness routing formulas (Spec 043 — Consciousness as Value Transparency).

This module implements the tensor-to-consciousness pipeline that replaces
the legacy ``ideological_routing.py``. Consciousness is NOT directly
incremented — it is the degree to which the value form becomes transparent
to those organized by it.

Pipeline Stages:
    1. **compute_agitation_delta()** — Converts changes in the value tensor
       (Δ(s/v), Δ(Φ), Δ(g₃₃)) into raw political energy (agitation).
    2. **compute_exploitation_visibility()** — Determines how visible
       exploitation is, dampened by imperial rent (commodity fetishism).
    3. **compute_reification_buffer()** — Measures how much commodity
       fetishism obscures class relations.
    4. **route_agitation_to_ternary()** — Routes accumulated agitation
       into (Δr, Δl, Δf) ternary consciousness shifts based on
       solidarity and education pressure.
    5. **normalize_to_simplex()** — Projects (r, l, f) onto the
       probability simplex (r + l + f = 1).

See Also:
    :class:`babylon.models.components.material_conditions.MaterialConditionsBuffer`:
        Stores the intermediate buffers on population nodes.
    :class:`babylon.models.entities.consciousness.TernaryConsciousness`:
        The canonical consciousness state on community hyperedges.
    :mod:`babylon.config.defines`: Tuning coefficients (ConsciousnessDefines).
"""

from __future__ import annotations

from babylon.config.defines import ConsciousnessDefines

_DEFAULT_DEFINES = ConsciousnessDefines()

# Division-by-zero guard
_EPSILON = 1e-10


def compute_agitation_delta(
    exploitation_rate_delta: float,
    imperial_rent_delta: float,
    visibility_delta: float,
    defines: ConsciousnessDefines | None = None,
) -> float:
    """Convert value tensor changes into agitation increment.

    Agitation is generated by three sources of material crisis:

    1. Rising exploitation rate (Δ(s/v) > 0): Workers produce more
       surplus relative to wages.
    2. Declining imperial rent (ΔΦ < 0): Core workers losing their
       bribe from unequal exchange.
    3. Increasing reproductive visibility (Δg₃₃ > 0): Previously
       invisible care work becoming monetized/contested.

    Formula::

        Δagitation = max(0, Δ(s/v)) × α_e
                   + max(0, -ΔΦ) × α_r
                   + max(0, Δg₃₃) × α_v

    Args:
        exploitation_rate_delta: Change in s/v since last tick.
        imperial_rent_delta: Change in Φ since last tick (negative = crisis).
        visibility_delta: Change in g₃₃ since last tick.
        defines: Optional custom coefficients.

    Returns:
        Non-negative agitation increment.
    """
    d = defines or _DEFAULT_DEFINES

    # Only positive Δ(s/v) generates agitation (more exploitation)
    exploit_component = max(0.0, exploitation_rate_delta) * d.exploitation_sensitivity

    # Only negative ΔΦ generates agitation (losing the bribe)
    rent_component = max(0.0, -imperial_rent_delta) * d.rent_decline_sensitivity

    # Only positive Δg₃₃ generates agitation (shadow labor becoming visible)
    vis_component = max(0.0, visibility_delta) * d.reproduction_visibility_coefficient

    return exploit_component + rent_component + vis_component


def compute_exploitation_visibility(
    exploitation_rate: float,
    imperial_rent: float,
    defines: ConsciousnessDefines | None = None,
) -> float:
    """Determine how visible exploitation is to a population.

    Imperial rent acts as an opacity filter on exploitation: when workers
    receive a "bribe" via unequal exchange with the periphery, the
    exploitation that does exist becomes obscured by material comfort.

    Formula::

        visibility = s/v / (s/v + Φ × opacity + ε)

    When Φ = 0 (periphery), visibility approaches 1.0 for high s/v.
    When Φ > 0 (core), visibility is dampened.

    Args:
        exploitation_rate: Current s/v ratio for this population.
        imperial_rent: Current Φ (positive = core, negative = periphery).
        defines: Optional custom coefficients.

    Returns:
        Exploitation visibility in [0, 1].
    """
    d = defines or _DEFAULT_DEFINES

    # Only positive rent obscures (periphery has negative rent — no obscuring)
    effective_rent = max(0.0, imperial_rent) * d.rent_opacity_factor
    denominator = exploitation_rate + effective_rent + _EPSILON

    if denominator <= 0:
        return 0.0

    raw_visibility = exploitation_rate / denominator
    return max(0.0, min(1.0, raw_visibility))


def compute_reification_buffer(
    imperial_rent: float,
    total_v: float,
) -> float:
    """Measure commodity fetishism from imperial rent.

    The reification buffer represents how much the commodity form
    obscures underlying class relations. Higher imperial rent means
    core workers experience class relations as "natural" rather than
    exploitative — the bribe makes the system appear to work.

    Formula::

        reification = |Φ| / (|Φ| + v + ε)

    Args:
        imperial_rent: Current Φ (positive or negative).
        total_v: Total variable capital in the local economy.
        defines: Optional custom coefficients.

    Returns:
        Reification buffer in [0, 1].
    """
    abs_rent = abs(imperial_rent)
    denominator = abs_rent + total_v + _EPSILON

    raw = abs_rent / denominator
    return max(0.0, min(1.0, raw))


def route_agitation_to_ternary(
    agitation: float,
    solidarity_factor: float,
    education_pressure: float,
    defines: ConsciousnessDefines | None = None,
) -> tuple[float, float, float]:
    """Route accumulated agitation into ternary consciousness shifts.

    Agitation is consumed and routed to (Δr, Δl, Δf) based on:

    1. **Solidarity** determines the revolutionary vs fascist split.
       With solidarity, agitation routes to r (class consciousness).
       Without solidarity, agitation routes to f (fascism).
    2. **Education pressure** biases the split toward revolutionary.
       This is the mechanized effect of the EDUCATE verb.
    3. **Liberal drain** absorbs a fraction as liberal drift.

    Formula::

        consumed = agitation × consumption_rate
        effective_solidarity = min(1.0, solidarity + education_pressure)
        Δr = consumed × effective_solidarity × routing_scale
        Δf = consumed × (1 - effective_solidarity) × routing_scale
        Δl = -(Δr + Δf) × liberal_backpressure

    Args:
        agitation: Accumulated agitation on this node [0, ∞).
        solidarity_factor: Incoming SOLIDARITY edge strength [0, 1].
        education_pressure: Education pressure on community [0, 1].
        defines: Optional custom coefficients.

    Returns:
        Tuple of (Δr, Δl, Δf) — directional shifts in ternary space.
        Δl is typically negative (agitation drains liberal tendency).
    """
    d = defines or _DEFAULT_DEFINES

    if agitation <= 0:
        return 0.0, 0.0, 0.0

    # Consume fraction of agitation for routing
    consumed = agitation * d.agitation_consumption_rate

    # Education pressure biases toward revolutionary
    effective_solidarity = min(1.0, solidarity_factor + education_pressure)

    # Scale factor for conversion
    scale = d.routing_scale

    # Route: solidarity → revolutionary, absence → fascist
    delta_r = consumed * effective_solidarity * scale
    delta_f = consumed * (1.0 - effective_solidarity) * scale

    # Liberal tendency absorbs the shift (net outflow from l)
    delta_l = -(delta_r + delta_f)

    return delta_r, delta_l, delta_f


def normalize_to_simplex(r: float, lib: float, f: float) -> tuple[float, float, float]:
    """Project (r, l, f) onto the probability simplex (r + l + f = 1).

    The simplex constraint ensures consciousness is a valid probability
    distribution. Values below zero are clamped. If the sum is below 1,
    the remainder is assigned to liberal (hegemonic default). If above 1,
    values are scaled proportionally.

    Args:
        r: Revolutionary tendency [may be any float].
        lib: Liberal tendency [may be any float].
        f: Fascist tendency [may be any float].

    Returns:
        Tuple of (r, lib, f) satisfying r + lib + f ≈ 1.0, all >= 0.
    """
    # Clamp negatives
    r = max(0.0, r)
    lib = max(0.0, lib)
    f = max(0.0, f)

    total = r + lib + f

    if total < _EPSILON:
        # All zeros → pure liberal default
        return 0.0, 1.0, 0.0

    if total > 1.0 + _EPSILON:
        # Scale down proportionally
        r /= total
        lib /= total
        f /= total
    elif total < 1.0 - _EPSILON:
        # Remainder goes to liberal (hegemonic default)
        lib += 1.0 - total

    return r, lib, f
