"""MaterialConditionsBuffer - Material preconditions for consciousness change.

The MaterialConditionsBuffer stores value-tensor-derived quantities on
population nodes that feed into community-level ternary consciousness
routing. It replaces the node-level ideological state with material
conditions that generate the possibility of consciousness change.

Consciousness is NOT stored here — it lives on community hyperedges
as TernaryConsciousness(r, l, f). This buffer stores the *inputs*
to consciousness change: agitation from crisis, exploitation visibility
from the value tensor, and reification from commodity fetishism.

Fields:
    agitation: Raw political energy from value tensor crisis [0, ∞).
        Generated by: Δ(s/v), Δ(Φ), Δ(wage), Δ(g₃₃), repression backfire.
    exploitation_visibility: How visible exploitation is to this pop [0, 1].
        Derived from: base_visibility + Δ(s/v) × sensitivity - Φ × opacity.
    reification_buffer: Commodity fetishism dampening [0, 1].
        Derived from: Φ / (Φ + v + ε) — higher rent = more obscured relations.

See Also:
    :class:`babylon.models.entities.consciousness.TernaryConsciousness`:
        The canonical consciousness state on community hyperedges.
    :mod:`babylon.formulas.consciousness_routing`: Routing formulas.
    :class:`babylon.config.defines.ConsciousnessDefines`: Tuning coefficients.
"""

from __future__ import annotations

from pydantic import BaseModel, ConfigDict, Field


class MaterialConditionsBuffer(BaseModel):
    """Material preconditions for consciousness change on a population node.

    This model stores the intermediate quantities derived from the value
    tensor (c/v/s) that feed into the community-level consciousness
    routing formula. It is NOT consciousness itself — consciousness
    lives on the community hyperedge as TernaryConsciousness.

    Args:
        agitation: Raw political energy from crisis conditions.
        exploitation_visibility: How clearly exploitation is visible.
        reification_buffer: How much commodity fetishism obscures relations.
    """

    model_config = ConfigDict(frozen=True)

    agitation: float = Field(
        default=0.0,
        ge=0.0,
        description="Raw political energy from value tensor crisis [0, inf)",
    )
    exploitation_visibility: float = Field(
        default=0.0,
        ge=0.0,
        le=1.0,
        description="How visible exploitation is to this population [0, 1]",
    )
    reification_buffer: float = Field(
        default=0.5,
        ge=0.0,
        le=1.0,
        description="Commodity fetishism dampening factor [0, 1]",
    )
