//! Exact current full-observer component views.

pub(crate) const OBSERVER_TICK_COMPONENT_VIEWS: [&str; 24] = [
    "public.v_observer_graph_node_v1",
    "public.v_observer_graph_node_f64_v1",
    "public.v_observer_graph_edge_v1",
    "public.v_observer_graph_hyperedge_v1",
    "public.v_observer_graph_hyperedge_member_v1",
    "public.v_observer_graph_edge_f64_v1",
    "public.v_observer_graph_node_currency_v1",
    "public.v_observer_graph_hyperedge_f64_v1",
    "public.v_observer_world_register_v1",
    "public.v_observer_hex_state_delta_v1",
    "public.v_observer_territory_state_v1",
    "public.v_observer_territory_state_field_v1",
    "public.v_observer_organization_state_v1",
    "public.v_observer_organization_state_field_v1",
    "public.v_observer_organization_territory_v1",
    "public.v_observer_tick_event_v2",
    "public.v_observer_tick_event_field_v2",
    "public.v_observer_tick_choice_receipt_v1",
    "public.v_observer_tick_choice_receipt_branch_v1",
    "public.v_observer_tick_choice_receipt_carrier_element_v1",
    "public.v_observer_checkpoint_manifest",
    "public.v_observer_checkpoint_section_v1",
    "public.v_observer_archive_dirty_receipt_v1",
    "public.v_observer_tick_action_batch_v1",
];
