"""Economic system database models based on Marxist economic theory.

These models capture the complex economic dynamics described in the game
documentation, including concepts from Marx's Capital such as:
- Rate of profit and its tendency to decline
- Organic composition of capital
- Surplus value and exploitation
- Class relations and contradictions
"""

from datetime import datetime
from enum import Enum as PyEnum
from typing import List, Optional

from sqlalchemy import (
    Column,
    DateTime,
    Enum,
    Float,
    ForeignKey,
    Index,
    Integer,
    JSON,
    String,
    Text,
)
from sqlalchemy.orm import Mapped, mapped_column, relationship

from ..database import Base


class EconomicPhase(PyEnum):
    """Economic cycle phases."""
    
    EXPANSION = "expansion"
    PEAK = "peak"
    CONTRACTION = "contraction"
    TROUGH = "trough"


class Economy(Base):
    """Represents the economic system state for a game.
    
    Tracks all economic indicators and Marxist metrics like rate of profit,
    organic composition of capital, and class relations.
    """
    
    __tablename__ = "economies"
    __table_args__ = (
        Index("idx_economy_game_turn", "game_id", "turn_number"),
    )
    
    id: Mapped[int] = mapped_column(Integer, primary_key=True)
    game_id: Mapped[int] = mapped_column(Integer, ForeignKey("games.id"), nullable=False)
    turn_number: Mapped[int] = mapped_column(Integer, nullable=False)
    
    # Basic economic indicators
    gdp: Mapped[float] = mapped_column(Float, nullable=False, default=1000.0)
    unemployment_rate: Mapped[float] = mapped_column(Float, default=5.0)  # percentage
    inflation_rate: Mapped[float] = mapped_column(Float, default=2.0)  # percentage
    gini_coefficient: Mapped[float] = mapped_column(Float, default=0.37)  # inequality measure
    
    # Marxist economic metrics
    constant_capital: Mapped[float] = mapped_column(Float, default=0.0)  # c - machinery, raw materials
    variable_capital: Mapped[float] = mapped_column(Float, default=0.0)  # v - wages, labor costs
    surplus_value: Mapped[float] = mapped_column(Float, default=0.0)  # s - profit generated by labor
    
    # Derived metrics
    organic_composition_capital: Mapped[Optional[float]] = mapped_column(Float)  # c/v
    rate_of_profit: Mapped[Optional[float]] = mapped_column(Float)  # s/(c+v)
    rate_of_surplus_value: Mapped[Optional[float]] = mapped_column(Float)  # s/v (exploitation rate)
    
    # Production and market
    production_capacity: Mapped[float] = mapped_column(Float, default=100.0)
    capacity_utilization: Mapped[float] = mapped_column(Float, default=0.75)
    market_demand: Mapped[float] = mapped_column(Float, default=100.0)
    market_supply: Mapped[float] = mapped_column(Float, default=100.0)
    price_level: Mapped[float] = mapped_column(Float, default=1.0)
    
    # Labor dynamics
    labor_productivity: Mapped[float] = mapped_column(Float, default=1.0)
    wage_share: Mapped[float] = mapped_column(Float, default=0.6)  # labor's share of income
    labor_force_participation: Mapped[float] = mapped_column(Float, default=0.65)
    
    # Crisis indicators
    economic_phase: Mapped[EconomicPhase] = mapped_column(
        Enum(EconomicPhase), default=EconomicPhase.EXPANSION
    )
    crisis_probability: Mapped[float] = mapped_column(Float, default=0.0)
    overproduction_level: Mapped[float] = mapped_column(Float, default=0.0)
    
    # Resource allocation
    resource_utilization: Mapped[float] = mapped_column(Float, default=0.75)
    waste_level: Mapped[float] = mapped_column(Float, default=0.1)
    sustainability_index: Mapped[float] = mapped_column(Float, default=0.5)
    
    # International trade (for modeling unequal exchange)
    export_value: Mapped[float] = mapped_column(Float, default=0.0)
    import_value: Mapped[float] = mapped_column(Float, default=0.0)
    terms_of_trade: Mapped[float] = mapped_column(Float, default=1.0)
    
    # Metadata
    created_at: Mapped[datetime] = mapped_column(
        DateTime, default=datetime.utcnow, nullable=False
    )
    
    # Additional context and notes
    economic_notes: Mapped[Optional[str]] = mapped_column(Text)
    policy_effects: Mapped[Optional[dict]] = mapped_column(JSON)
    
    # Relationships
    game: Mapped["Game"] = relationship("Game", back_populates="economies")
    economic_timeseries: Mapped[List["EconomicTimeSeries"]] = relationship(
        "EconomicTimeSeries", back_populates="economy"
    )
    class_relations: Mapped[List["ClassRelation"]] = relationship(
        "ClassRelation", back_populates="economy"
    )
    
    def calculate_derived_metrics(self) -> None:
        """Calculate derived economic metrics from base values."""
        # Organic composition of capital (c/v)
        if self.variable_capital > 0:
            self.organic_composition_capital = self.constant_capital / self.variable_capital
        else:
            self.organic_composition_capital = None
            
        # Rate of profit: s/(c+v)
        total_capital = self.constant_capital + self.variable_capital
        if total_capital > 0:
            self.rate_of_profit = self.surplus_value / total_capital
        else:
            self.rate_of_profit = None
            
        # Rate of surplus value (exploitation rate): s/v
        if self.variable_capital > 0:
            self.rate_of_surplus_value = self.surplus_value / self.variable_capital
        else:
            self.rate_of_surplus_value = None


class EconomicTimeSeries(Base):
    """Time series data for tracking economic indicators over time.
    
    This allows for analysis of trends and patterns in economic development,
    particularly useful for modeling Marx's tendency of rate of profit to decline.
    """
    
    __tablename__ = "economic_timeseries"
    __table_args__ = (
        Index("idx_timeseries_economy_metric", "economy_id", "metric_name", "timestamp"),
    )
    
    id: Mapped[int] = mapped_column(Integer, primary_key=True)
    economy_id: Mapped[int] = mapped_column(Integer, ForeignKey("economies.id"), nullable=False)
    
    # Metric identification
    metric_name: Mapped[str] = mapped_column(String(100), nullable=False)
    metric_value: Mapped[float] = mapped_column(Float, nullable=False)
    
    # Time and context
    timestamp: Mapped[datetime] = mapped_column(
        DateTime, default=datetime.utcnow, nullable=False
    )
    turn_number: Mapped[int] = mapped_column(Integer, nullable=False)
    
    # Additional context
    category: Mapped[Optional[str]] = mapped_column(String(50))  # e.g., "production", "distribution"
    notes: Mapped[Optional[str]] = mapped_column(Text)
    
    # Relationships
    economy: Mapped["Economy"] = relationship("Economy", back_populates="economic_timeseries")


class ClassRelation(Base):
    """Represents class relations and dynamics in the economic system.
    
    Models the relationship between different social classes based on
    their relationship to the means of production.
    """
    
    __tablename__ = "class_relations"
    __table_args__ = (
        Index("idx_class_economy_class", "economy_id", "class_name"),
    )
    
    id: Mapped[int] = mapped_column(Integer, primary_key=True)
    economy_id: Mapped[int] = mapped_column(Integer, ForeignKey("economies.id"), nullable=False)
    
    # Class identification
    class_name: Mapped[str] = mapped_column(String(100), nullable=False)  # e.g., "proletariat", "bourgeoisie"
    class_description: Mapped[Optional[str]] = mapped_column(Text)
    
    # Class metrics
    population_percentage: Mapped[float] = mapped_column(Float, default=0.0)
    income_share: Mapped[float] = mapped_column(Float, default=0.0)
    wealth_share: Mapped[float] = mapped_column(Float, default=0.0)
    
    # Political and social indicators
    class_consciousness: Mapped[float] = mapped_column(Float, default=0.0)  # 0.0 to 1.0
    political_influence: Mapped[float] = mapped_column(Float, default=0.0)
    organization_level: Mapped[float] = mapped_column(Float, default=0.0)
    
    # Relations to means of production
    owns_means_production: Mapped[bool] = mapped_column(default=False)
    sells_labor_power: Mapped[bool] = mapped_column(default=False)
    
    # Additional attributes
    attributes: Mapped[Optional[dict]] = mapped_column(JSON)
    
    # Timestamps
    created_at: Mapped[datetime] = mapped_column(
        DateTime, default=datetime.utcnow, nullable=False
    )
    
    # Relationships
    economy: Mapped["Economy"] = relationship("Economy", back_populates="class_relations")


class ProductionSector(Base):
    """Represents different sectors of production in the economy.
    
    Allows modeling of sectoral differences and the flow of commodities
    between sectors as described in Marx's Capital Volume 2.
    """
    
    __tablename__ = "production_sectors"
    
    id: Mapped[int] = mapped_column(Integer, primary_key=True)
    economy_id: Mapped[int] = mapped_column(Integer, ForeignKey("economies.id"), nullable=False)
    
    # Sector identification
    sector_name: Mapped[str] = mapped_column(String(100), nullable=False)
    sector_type: Mapped[str] = mapped_column(String(50))  # e.g., "primary", "secondary", "tertiary"
    description: Mapped[Optional[str]] = mapped_column(Text)
    
    # Production metrics
    output_value: Mapped[float] = mapped_column(Float, default=0.0)
    input_costs: Mapped[float] = mapped_column(Float, default=0.0)
    labor_hours: Mapped[float] = mapped_column(Float, default=0.0)
    
    # Capital composition
    constant_capital: Mapped[float] = mapped_column(Float, default=0.0)
    variable_capital: Mapped[float] = mapped_column(Float, default=0.0)
    
    # Efficiency and productivity
    productivity_index: Mapped[float] = mapped_column(Float, default=1.0)
    automation_level: Mapped[float] = mapped_column(Float, default=0.0)
    
    # Market position
    market_share: Mapped[float] = mapped_column(Float, default=0.0)
    competitiveness: Mapped[float] = mapped_column(Float, default=0.5)
    
    # Timestamps
    created_at: Mapped[datetime] = mapped_column(
        DateTime, default=datetime.utcnow, nullable=False
    )
    updated_at: Mapped[Optional[datetime]] = mapped_column(DateTime)
    
    # Additional data
    sector_data: Mapped[Optional[dict]] = mapped_column(JSON)