-- 0039_domain_contracts.sql
-- ledger-contracts: PostgreSQL CREATE DOMAIN types that lift the range/format
-- contracts of src/babylon/models/types.py into single, language-agnostic,
-- byte-checkable objects (the "rewrite test" — a DOMAIN proves the invariant
-- regardless of which language writes the row).
--
-- GENERATED by tools/generate_domain_ddl.py. The numeric domains' bounds are
-- read from the annotated_types metadata on the models/types.py constrained
-- types; the fips/h3 format literals come from
-- babylon.sentinels.domain_sync.registry. DO NOT hand-edit a CHECK below —
-- change models/types.py (numeric) or the registry (format) and regenerate
-- (uv run python tools/generate_domain_ddl.py). The domain_sync sentinel reds
-- the gate on any drift between this file and those sources.
--
-- ENFORCE, NEVER COMPUTE: each DOMAIN carries a CHECK only — no GENERATED
-- column, no trigger, no float arithmetic (the engine computes; the ledger
-- validates). A DOMAIN is a RANGE gate, not a precision gate: it enforces the
-- ge/le/gt range (VALUE >= .. [AND VALUE <= ..]); the SnapToGrid 1e-5/1e-6
-- QUANTIZATION the same types apply stays app-side — that is compute, and it
-- is Pydantic's job, not the ledger's.
--
-- NULL policy: domains are NULLABLE — a SQL CHECK is not-false on NULL, so
-- column-level NOT NULL stays each column's own decision (many ledger columns
-- are NOT NULL, some are not). Adding a domain here never forces nullability.
--
-- Idempotent: PostgreSQL has no CREATE DOMAIN IF NOT EXISTS, so every domain
-- is guarded on pg_type (typtype='d', current schema) inside one DO block —
-- the runner re-applies every migration on each start (see migration 0027).
--
-- SQLite-reference asymmetry: the read-only reference DB (SQLite) has no
-- DOMAINs; that lane keeps its app-side / inline enforcement. Out of scope
-- here — documented, not silently implied (ADR138).

DO $domain_contracts$
BEGIN
    -- numeric range domains (bounds generated from models/types.py) --------
    IF NOT EXISTS (
        SELECT 1 FROM pg_type t JOIN pg_namespace n ON n.oid = t.typnamespace
        WHERE t.typname = 'probability' AND t.typtype = 'd' AND n.nspname = current_schema()
    ) THEN
        CREATE DOMAIN probability AS double precision CHECK (VALUE >= 0.0 AND VALUE <= 1.0);
    END IF;
    IF NOT EXISTS (
        SELECT 1 FROM pg_type t JOIN pg_namespace n ON n.oid = t.typnamespace
        WHERE t.typname = 'currency' AND t.typtype = 'd' AND n.nspname = current_schema()
    ) THEN
        CREATE DOMAIN currency AS double precision CHECK (VALUE >= 0.0);
    END IF;
    IF NOT EXISTS (
        SELECT 1 FROM pg_type t JOIN pg_namespace n ON n.oid = t.typnamespace
        WHERE t.typname = 'ratio' AND t.typtype = 'd' AND n.nspname = current_schema()
    ) THEN
        CREATE DOMAIN ratio AS double precision CHECK (VALUE > 0.0);
    END IF;
    IF NOT EXISTS (
        SELECT 1 FROM pg_type t JOIN pg_namespace n ON n.oid = t.typnamespace
        WHERE t.typname = 'labor_hours' AND t.typtype = 'd' AND n.nspname = current_schema()
    ) THEN
        CREATE DOMAIN labor_hours AS double precision CHECK (VALUE >= 0.0);
    END IF;
    -- string-format domains (patterns declared in the domain_sync registry) -
    IF NOT EXISTS (
        SELECT 1 FROM pg_type t JOIN pg_namespace n ON n.oid = t.typnamespace
        WHERE t.typname = 'fips5' AND t.typtype = 'd' AND n.nspname = current_schema()
    ) THEN
        CREATE DOMAIN fips5 AS text CHECK (VALUE ~ '^\d{5}$');
    END IF;
    IF NOT EXISTS (
        SELECT 1 FROM pg_type t JOIN pg_namespace n ON n.oid = t.typnamespace
        WHERE t.typname = 'fips2' AND t.typtype = 'd' AND n.nspname = current_schema()
    ) THEN
        CREATE DOMAIN fips2 AS text CHECK (VALUE ~ '^\d{2}$');
    END IF;
    IF NOT EXISTS (
        SELECT 1 FROM pg_type t JOIN pg_namespace n ON n.oid = t.typnamespace
        WHERE t.typname = 'h3index' AND t.typtype = 'd' AND n.nspname = current_schema()
    ) THEN
        CREATE DOMAIN h3index AS text CHECK (length(VALUE) = 15);
    END IF;
END
$domain_contracts$;
