# Ansible Inventory - Generated by Terraform
# Format: INI

[all]
%{ for server in servers ~}
${server.name} ansible_host=${server.ip} ansible_user=root%{ if server.private_ip != null } private_ip=${server.private_ip}%{ endif }
%{ endfor ~}

[webservers]
%{ for server in servers ~}
${server.name}
%{ endfor ~}

[all:vars]
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
ansible_python_interpreter=/usr/bin/python3
ansible_ssh_private_key_file=${ssh_private_key_path}
