# Ansible Inventory - Generated by Terraform
# Format: YAML

all:
  hosts:
%{ for server in servers ~}
    ${server.name}:
      ansible_host: ${server.ip}
      ansible_user: root
%{ if server.private_ip != null ~}
      private_ip: ${server.private_ip}
%{ endif ~}
%{ endfor ~}
  vars:
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
    ansible_python_interpreter: /usr/bin/python3
