"""Contract Parity Test for HexMap.

Proves that the shape of data coming from the live API matches the shape
of the mock fixture. If this passes, React can swap from mock to live
with zero changes.
"""

import json
import uuid
from pathlib import Path

import pytest
from django.contrib.auth.models import User
from django.core.management import call_command
from django.test import Client

import game.api
from game.engine_bridge import EngineBridge
from game.models import GameSession, HexState


@pytest.mark.django_db
@pytest.mark.integration
class TestContractParity:
    """Proves API response shape matches mock fixture shape."""

    def test_api_response_shape_matches_fixture(self):
        # Load fixture
        fixture_path = (
            Path(__file__).parent.parent.parent.parent
            / "web"
            / "frontend"
            / "src"
            / "fixtures"
            / "mock_map_data.json"
        )
        with open(fixture_path) as f:
            mock_data = json.load(f)

        # We will test the API by initializing an EngineBridge with a dummy persistence layer,
        # but wait, `get_map_snapshot` uses Django models directly in EngineBridge anyway!
        # So we can just use a MagicMock for persistence.

        from unittest.mock import MagicMock

        mock_persistence = MagicMock()
        bridge = EngineBridge(mock_persistence)

        # Create session
        user = User.objects.create_user(username="parityuser", password="paritypass123")  # type: ignore[no-untyped-call]
        session_id = uuid.uuid4()
        session = GameSession.objects.create(
            id=session_id,
            player_id=user.id,
            scenario="test_scenario",
            current_tick=0,
            status="active",
        )

        # Seed Postgres (or SQLite test DB) from fixture
        # The management command uses the fixture path correctly
        call_command("seed_hex_data", str(session.id), fixture=str(fixture_path))

        # Verify seeding succeeded
        assert HexState.objects.filter(game=session).count() > 0

        # Inject real bridge
        client = Client()
        client.login(username="parityuser", password="paritypass123")
        game.api._bridge_instance = bridge

        # Hit API endpoint
        response = client.get(f"/api/games/{session.id}/map/")
        assert response.status_code == 200

        api_response = json.loads(response.content)
        assert api_response["status"] == "ok"
        api_data = api_response["data"]

        # Assert: top-level keys identical
        # The mock is just a FeatureCollection. The API envelopes it in {"status": "ok", "data": ...}
        assert api_data["type"] == mock_data["type"]
        assert "features" in api_data
        assert "metadata" in api_data

        # Assert: metadata keys — fixture keys are subset of API keys
        mock_metadata = mock_data.get("metadata", {})
        api_metadata = api_data.get("metadata", {})

        for key in mock_metadata:
            if key == "bounds":
                continue  # Bounds was not strictly generated by API, optional in React map anyway
            assert key in api_metadata

        # Assert: feature property keys identical
        if mock_data["features"]:
            mock_feature = mock_data["features"][0]
            api_feature = api_data["features"][0]

            # Assert feature geometry type is Polygon
            assert mock_feature["geometry"]["type"] == api_feature["geometry"]["type"] == "Polygon"

            # Assert feature has id field
            assert "id" in api_feature

            # Assert property keys identical
            mock_props = set(mock_feature["properties"].keys())
            api_props = set(api_feature["properties"].keys())

            assert mock_props == api_props
