"""Deterministic ``CREATE DOMAIN`` rendering from the ``domain_sync`` registry.

The single place that turns a :mod:`babylon.sentinels.domain_sync.registry`
spec into SQL. Both consumers import from here so there is exactly one renderer:

- ``tools/generate_domain_ddl.py`` calls :func:`build_migration_sql` to WRITE
  ``0039_domain_contracts.sql`` (and, with ``--check``, to verify the committed
  file is in sync);
- :mod:`babylon.sentinels.domain_sync.checks` calls :func:`numeric_check_predicate`
  / :func:`format_check_predicate` to derive the EXPECTED ``CHECK`` body live and
  compare it against the committed file's parsed body.

Because the sentinel derives its expectation from :mod:`babylon.models.types`
(numeric) and the registry (format) — never from a cached copy of the
generator's output — a drift on EITHER side (a ``types.py`` bound change the
migration did not follow, or a hand-edit of the migration) reddens the gate.

**Enforce, never compute.** Every predicate rendered here is a ``CHECK`` body:
a range comparison (``VALUE >= 0.0``), a regex match (``VALUE ~ '...'``), or a
builtin-length equality (``length(VALUE) = 15``). No ``GENERATED`` column, no
trigger, no float arithmetic — the domain is a RANGE gate, not a precision
gate. The 1e-5/1e-6 ``SnapToGrid`` quantization the same ``types.py`` types
apply is app-side compute (Pydantic's job), deliberately NOT mirrored here.

Layer 0.5: imports :mod:`babylon.models.types` (the ceiling) and stdlib only.
"""

from __future__ import annotations

from typing import Final, NamedTuple

import annotated_types as at

from babylon.models import types as babylon_types
from babylon.sentinels.base import SentinelCheckError
from babylon.sentinels.domain_sync.registry import (
    FORMAT_DOMAINS,
    NUMERIC_DOMAINS,
    FormatDomainSpec,
    NumericDomainSpec,
)

__all__ = [
    "Bounds",
    "build_migration_sql",
    "format_check_predicate",
    "numeric_check_predicate",
    "types_py_bounds",
]

#: Dollar-quote tag for the single idempotent DO block (kept distinct so a
#: nested ``$$`` in any future predicate can never terminate the block early).
_DO_TAG: Final[str] = "domain_contracts"

# The generated-file header. Mirrors the 0037/0038 comment style. Kept verbatim
# so the codegen output is byte-stable; every claim here is enforced elsewhere
# (idempotency by the DO guards, sync by the domain_sync sentinel).
_HEADER: Final[str] = """\
-- {filename}
-- ledger-contracts: PostgreSQL CREATE DOMAIN types that lift the range/format
-- contracts of src/babylon/models/types.py into single, language-agnostic,
-- byte-checkable objects (the "rewrite test" — a DOMAIN proves the invariant
-- regardless of which language writes the row).
--
-- GENERATED by tools/generate_domain_ddl.py. The numeric domains' bounds are
-- read from the annotated_types metadata on the models/types.py constrained
-- types; the fips/h3 format literals come from
-- babylon.sentinels.domain_sync.registry. DO NOT hand-edit a CHECK below —
-- change models/types.py (numeric) or the registry (format) and regenerate
-- (uv run python tools/generate_domain_ddl.py). The domain_sync sentinel reds
-- the gate on any drift between this file and those sources.
--
-- ENFORCE, NEVER COMPUTE: each DOMAIN carries a CHECK only — no GENERATED
-- column, no trigger, no float arithmetic (the engine computes; the ledger
-- validates). A DOMAIN is a RANGE gate, not a precision gate: it enforces the
-- ge/le/gt range (VALUE >= .. [AND VALUE <= ..]); the SnapToGrid 1e-5/1e-6
-- QUANTIZATION the same types apply stays app-side — that is compute, and it
-- is Pydantic's job, not the ledger's.
--
-- NULL policy: domains are NULLABLE — a SQL CHECK is not-false on NULL, so
-- column-level NOT NULL stays each column's own decision (many ledger columns
-- are NOT NULL, some are not). Adding a domain here never forces nullability.
--
-- Idempotent: PostgreSQL has no CREATE DOMAIN IF NOT EXISTS, so every domain
-- is guarded on pg_type (typtype='d', current schema) inside one DO block —
-- the runner re-applies every migration on each start (see migration 0027).
--
-- SQLite-reference asymmetry: the read-only reference DB (SQLite) has no
-- DOMAINs; that lane keeps its app-side / inline enforcement. Out of scope
-- here — documented, not silently implied (ADR138)."""


class Bounds(NamedTuple):
    """The extracted range of a ``models.types`` constrained type.

    :ivar lower: The lower bound value, or ``None`` if unbounded below.
    :ivar lower_inclusive: ``True`` for ``ge`` (>=), ``False`` for ``gt`` (>).
    :ivar upper: The upper bound value, or ``None`` if unbounded above.
    :ivar upper_inclusive: ``True`` for ``le`` (<=), ``False`` for ``lt`` (<).
    """

    lower: float | None
    lower_inclusive: bool
    upper: float | None
    upper_inclusive: bool


def _resolve_type(source_type: str) -> object:
    """Resolve a ``models.types`` attribute name to its Annotated type object.

    :param source_type: The attribute name (e.g. ``"Probability"``).
    :returns: The Annotated type object.
    :raises SentinelCheckError: If the name is not present on
        :mod:`babylon.models.types` (registry drift — a listed source type was
        renamed or removed).
    """
    obj = getattr(babylon_types, source_type, None)
    if obj is None:
        raise SentinelCheckError(
            f"domain_sync: models.types has no attribute {source_type!r} "
            "(NUMERIC_DOMAINS registry drift — update or remove the row)"
        )
    return obj


def types_py_bounds(type_obj: object) -> Bounds:
    """Extract the ``ge``/``le``/``gt``/``lt`` range off an Annotated type.

    Reads the ``annotated_types`` constraints Pydantic records on the field
    metadata — the same mechanism ``tools/generate_defines_config.py`` uses to
    render its range comments — so the bound seen here is byte-for-byte the one
    ``types.py`` declares.

    :param type_obj: An ``Annotated[float, Field(...), ...]`` type object.
    :returns: The extracted :class:`Bounds`.
    :raises SentinelCheckError: If the type carries no range constraint at all
        (an unbounded type has no CHECK to express — it must never be listed as
        a numeric domain).
    """
    lower: float | None = None
    lower_inclusive = True
    upper: float | None = None
    upper_inclusive = True
    for meta in getattr(type_obj, "__metadata__", ()):
        inner = getattr(meta, "metadata", None)
        constraints = inner if inner is not None else [meta]
        for constraint in constraints:
            if isinstance(constraint, at.Ge):
                lower, lower_inclusive = float(constraint.ge), True  # type: ignore[arg-type]
            elif isinstance(constraint, at.Gt):
                lower, lower_inclusive = float(constraint.gt), False  # type: ignore[arg-type]
            elif isinstance(constraint, at.Le):
                upper, upper_inclusive = float(constraint.le), True  # type: ignore[arg-type]
            elif isinstance(constraint, at.Lt):
                upper, upper_inclusive = float(constraint.lt), False  # type: ignore[arg-type]
    if lower is None and upper is None:
        raise SentinelCheckError(
            "domain_sync: resolved a numeric-domain source type with no ge/le/gt/lt "
            "range — an unbounded type has no CHECK and must not be a domain"
        )
    return Bounds(lower, lower_inclusive, upper, upper_inclusive)


def _fmt_float(value: float) -> str:
    """Render a bound as a stable SQL float literal (``0.0``, ``1.0``, ``-1.0``).

    :param value: The bound value.
    :returns: ``repr(float(value))`` — deterministic and round-trippable.
    """
    return repr(float(value))


def numeric_check_predicate(spec: NumericDomainSpec) -> str:
    """The canonical ``CHECK`` body for a numeric domain, derived from ``types.py``.

    :param spec: The numeric domain spec (names the ``types.py`` source type).
    :returns: e.g. ``"VALUE >= 0.0 AND VALUE <= 1.0"`` or ``"VALUE > 0.0"``.
    :raises SentinelCheckError: If the source type is unresolved or unbounded.
    """
    bounds = types_py_bounds(_resolve_type(spec.source_type))
    conjuncts: list[str] = []
    if bounds.lower is not None:
        op = ">=" if bounds.lower_inclusive else ">"
        conjuncts.append(f"VALUE {op} {_fmt_float(bounds.lower)}")
    if bounds.upper is not None:
        op = "<=" if bounds.upper_inclusive else "<"
        conjuncts.append(f"VALUE {op} {_fmt_float(bounds.upper)}")
    return " AND ".join(conjuncts)


def format_check_predicate(spec: FormatDomainSpec) -> str:
    """The canonical ``CHECK`` body for a format domain, from the registry.

    :param spec: The format domain spec.
    :returns: ``"VALUE ~ '<pattern>'"`` (regex) or ``"length(VALUE) = <n>"``
        (length). No float arithmetic — a regex match / integer length equality.
    """
    if spec.kind == "regex":
        return f"VALUE ~ '{spec.pattern}'"
    return f"length(VALUE) = {spec.pattern}"


def _guarded_domain_block(name: str, sql_base: str, predicate: str) -> str:
    """One idempotent guarded CREATE DOMAIN statement for the DO block.

    :param name: The domain name.
    :param sql_base: The SQL base type.
    :param predicate: The rendered CHECK body (the ``VALUE ...`` clause).
    :returns: The four-line guarded block (pg_type existence check + create).
    """
    # Generated DDL, not a runtime query: name/sql_base/predicate all come from
    # the frozen, import-validated domain_sync registry (names are
    # `.isidentifier()`-checked), never user input — hence the S608 suppression.
    guard = f"""\
    IF NOT EXISTS (
        SELECT 1 FROM pg_type t JOIN pg_namespace n ON n.oid = t.typnamespace
        WHERE t.typname = '{name}' AND t.typtype = 'd' AND n.nspname = current_schema()
    ) THEN
        CREATE DOMAIN {name} AS {sql_base} CHECK ({predicate});
    END IF;"""  # noqa: S608
    return guard


def build_migration_sql(filename: str = "0039_domain_contracts.sql") -> str:
    """Render the full ``0039_domain_contracts.sql`` migration text.

    Deterministic: domains are emitted in registry order (numeric first, then
    format), each guarded. The output is what ``tools/generate_domain_ddl.py``
    writes and what the ``domain_sync`` sentinel expects the committed file to
    equal.

    :param filename: The filename stamped into the header comment.
    :returns: The complete migration file text (trailing newline included).
    :raises SentinelCheckError: If any numeric source type is unresolved/unbounded.
    """
    blocks: list[str] = [
        "    -- numeric range domains (bounds generated from models/types.py) --------",
    ]
    for numeric in NUMERIC_DOMAINS:
        blocks.append(
            _guarded_domain_block(numeric.name, numeric.sql_base, numeric_check_predicate(numeric))
        )
    blocks.append("    -- string-format domains (patterns declared in the domain_sync registry) -")
    for fmt in FORMAT_DOMAINS:
        blocks.append(_guarded_domain_block(fmt.name, fmt.sql_base, format_check_predicate(fmt)))

    body = "\n".join(blocks)
    header = _HEADER.format(filename=filename)
    return f"{header}\n\nDO ${_DO_TAG}$\nBEGIN\n{body}\nEND\n${_DO_TAG}$;\n"
