"use strict";

// A finite presentation walkthrough. These branches are authored fixtures,
// never an action resolver, knowledge grant, campaign ledger or simulation.
const initialState = () => ({ stage: "quiet", choice: "inquiry", note: "Check whose shifts were reduced and what workers can sustain before promising a wider campaign.", routinePaused: false, ruling: null, partner: "limited", eligible: true, admission: "accepted", completed: false });
let state = initialState();
let evidenceOpener = null;
const $ = (id) => document.getElementById(id);
const escapeHtml = (value) => value.replace(/[&<>"']/g, (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" })[c]);
const choices = {
  inquiry: { title: "Inquiry", hours: 12, purpose: "Establish whose income is threatened and which account of the stoppage holds up.", practice: "A bounded inquiry into the workplace report", cost: "12 organizer-hours; neighborhood routine displaced for Period 3.", limit: "No promise that someone will respond or that lost income will be restored." },
  reinforce: { title: "Reinforce the existing tie", hours: 8, purpose: "Sustain the eligible workplace committee relationship while shifts are reduced.", practice: "A bounded practice on the existing workplace tie", cost: "8 organizer-hours; neighborhood routine displaced for Period 3.", limit: "No recruitment, new membership, coalition or authority over the committee." },
  hold: { title: "Hold this situation", hours: 0, purpose: "Make no special commitment while preserving the current scope of standing work.", practice: "No special practice; eligible standing work continues", cost: "Standing work still costs 8 organizer-hours unless separately paused.", limit: "No targeted new inquiry or workplace practice; the income pressure continues." }
};
const stageNames = { quiet: "1 · Routine", situation: "2 · Reduced shifts", alternatives: "3 · Approaches", review: "4 · Player ruling", submitted: "5 · Submitted", resolving: "6 · Resolving", completed: "7 · Feedback", appraisal: "8 · Revised situation" };
const locked = () => state.ruling !== null;
const effectiveChoice = () => state.ruling || state.choice;
const isSpecial = () => effectiveChoice() !== "hold";
const practiceDescription = () => isSpecial() ? choices[effectiveChoice()].practice : state.routinePaused ? "No practice; standing work separately paused" : "Previously authorized neighborhood routine; no special practice";
const period = () => state.stage === "quiet" ? 1 : state.completed ? 3 : 2;
const routineNext = () => state.routinePaused ? "Paused by player" : !state.eligible && state.completed ? "Paused · scope unavailable; review required" : "Eligible · continues within the same authorization";
const previewing = () => ["alternatives", "review"].includes(state.stage);
const hours = () => (!locked() && !previewing()) ? (state.routinePaused ? 0 : 8) : isSpecial() ? choices[effectiveChoice()].hours : state.routinePaused ? 0 : 8;
function announce(text) { $("announcement").textContent = text; }
function go(stage) { state.stage = stage; render(); $("screen").focus(); }
function evidenceLinks() { return '<div class="evidence-links"><button data-evidence="material">Workplace and material evidence</button><button data-evidence="relationship">People and existing relationship</button><button data-evidence="direction">Direction and disagreements</button></div>'; }
function record() { return `<div class="callout"><strong>${locked() ? "Recorded" : "Draft"} intention</strong><p>${choices[effectiveChoice()].purpose}</p><strong>Player's review note</strong><p>${escapeHtml(state.note) || "No additional note recorded."}</p></div>`; }
function partnerText() { return ({ limited: "The independent partner offers a private inquiry conversation. It has not agreed to a public campaign or supplied a collective mandate.", declined: "The independent partner declines cooperation. Our ruling stands; its resources and participation remain outside our control.", pending: "No reply has been received. Silence is not agreement, refusal or a hidden response score." })[state.partner]; }
function render() {
  $("period-label").textContent = state.stage === "resolving" ? "PERIOD 3" : `PERIOD ${period()}`;
  $("lifecycle").textContent = state.stage === "resolving" ? "Resolving · last completed: 2" : stageNames[state.stage].split(" · ")[1];
  $("journey").innerHTML = Object.entries(stageNames).map(([key, value]) => `<span${key === state.stage ? ' aria-current="step"' : ""}>${value}</span>`).join("");
  $("allocation").innerHTML = `<strong>${locked() ? "Period 3 allocation" : previewing() ? "Preview · Period 3 allocation" : "Planned standing work · Period 3"}</strong>${hours()} / 16 organizer-hours · ${hours() ? "1 / 1" : "0 / 1"} practice slot`;
  $("routine-state").textContent = `Period ${state.completed ? 4 : 3} · ${state.routinePaused ? "Paused by player" : locked() && isSpecial() && !state.completed ? "Replaced for this period only" : routineNext()}`;
  $("pause-routine").textContent = state.routinePaused ? "Resume standing work" : "Pause standing work";
  $("pause-routine").disabled = locked();
  $("pause-help").textContent = locked() ? "The recorded Period 3 allocation cannot be edited here. Next-period eligibility is reviewed after feedback." : "Takes effect in Period 3. Does not alter a completed period. Hold is a different decision.";
  $("selection").textContent = "Selection retained: Wayne metal-parts workplace / affected workplace committee";
  for (const id of ["partner", "eligibility", "admission"]) $(id).disabled = locked();
  $("partner").value = state.partner; $("eligibility").value = state.eligible ? "eligible" : "ineligible"; $("admission").value = state.admission;
  const screens = {
    quiet: () => `<span class="eyebrow">QUIET PERIOD · EXPLICIT STANDING AUTHORIZATION</span><h2>Our routine continues without another meeting.</h2><p class="lead">The neighborhood committee relationship is already in scope. The organization uses its one practice slot to maintain that tie.</p><div class="callout"><strong>Period 1 routine record · fixture</strong><p>8 organizer-hours used. Contact completed; a committee report was received. No membership, coalition or wider campaign was created.</p><button data-evidence="routine">Inspect the routine record</button></div><p>The pinned income-protection intention stays visible. Pinning it has spent nothing and submitted no action.</p><div class="actions"><button class="primary" data-go="situation">Continue to the Period 2 report</button></div>`,
    situation: () => `<span class="eyebrow">REPORTED · WORKPLACE COMMITTEE · PERIOD 2</span><h2>Reduced shifts threaten workers' income.</h2><p class="lead">The workplace committee reports fewer shifts at Wayne's metal-parts workplace. Management attributes the stoppage to a production constraint. The committee asks us to establish what can be done.</p><dl class="facts"><dt>What is at stake</dt><dd>Income and the time workers can sustain collective activity. Lost wages are not quantified in this example.</dd><dt>Whom we represent</dt><dd>Our organizing collective. The committee is an existing contact, not the entire workforce.</dd><dt>What we can decide</dt><dd>Our own bounded practice and use of local capacity. Other actors decide their participation.</dd><dt>What is uncertain</dt><dd>Who bore the shift reduction, which account is reliable, and what cooperation is available.</dd></dl>${evidenceLinks()}<div class="actions"><button class="primary" data-go="alternatives">Compare approaches</button></div>`,
    alternatives: () => `<span class="eyebrow">ONE SITUATION · DISTINCT COMMITMENTS</span><h2>What should we do in Period 3?</h2><p>Choose an approach before making the organizational ruling. None of these choices directly restores factory output or wages.</p><div class="options">${Object.entries(choices).map(([id, c]) => `<button class="option" data-choice="${id}" aria-pressed="${state.choice === id}"><span data-choice-label>${c.title}${state.choice === id ? " · Selected" : ""}</span><span>${c.purpose}</span><span>${c.cost}</span></button>`).join("")}</div><label for="draft-note">Draft purpose / condition for revision</label><textarea id="draft-note">${escapeHtml(state.note)}</textarea>${evidenceLinks()}<div class="actions"><button data-go="situation">Back to situation</button><button class="primary" data-go="review">Review selected approach</button></div>`,
    review: () => `<span class="eyebrow">DRAFT · PLAYER IS FINAL ORGANIZATIONAL ARBITER</span><h2>${choices[state.choice].title}</h2>${record()}<dl class="facts"><dt>Our commitment</dt><dd>${practiceDescription()}.</dd><dt>Allocation</dt><dd>${state.choice === "hold" ? (state.routinePaused ? "0 hours; standing work separately paused." : "8 hours for standing work; 8 remain outside this practice.") : `${choices[state.choice].hours} hours; ${16 - choices[state.choice].hours} remain outside this practice.`} No second practice is admitted just because hours remain.</dd><dt>Routine effect</dt><dd>${state.choice === "hold" ? (state.routinePaused ? "Hold adds no special practice. Your separate Pause remains in effect." : "Hold continues the existing routine; it does not pause it.") : state.routinePaused ? "Standing work was already paused separately. The special practice uses Period 3; the explicit Pause remains in effect afterward." : "The special commitment replaces standing work for Period 3 only. The same routine resumes for Period 4 if still eligible; otherwise it pauses for review."}</dd><dt>Independent actors</dt><dd>The partner's participation is unresolved here. The workplace committee has not authorized a public campaign.</dd><dt>Limits</dt><dd>${choices[state.choice].limit}</dd><dt>Resolving period</dt><dd>Period 3 · next 28-day committed tick. Drafting creates no material effect.</dd><dt>Reopen if</dt><dd>Shifts remain reduced, cooperation changes, participation cannot be sustained, or routine scope becomes unavailable.</dd></dl>${evidenceLinks()}<p class="muted">Normal material and authority admission still applies. No NPC vote may replace an eligible player ruling. Disagreement and willingness to participate remain consequential.</p><div class="actions"><button data-go="alternatives">Revise draft</button><button class="primary" id="submit">Confirm organizational ruling · fixture</button></div><p id="refusal" role="status"></p>`,
    submitted: () => `<span class="eyebrow">SUBMITTED · FIXTURE ADMISSION ACKNOWLEDGED</span><h2>The selected direction is recorded.</h2>${record()}<p>${practiceDescription()}. The commitment targets Period 3. No new knowledge, relational effect or material recovery is credited at submission.</p><p>Normal admission has accepted this example. Partner agreement is not implied. There is no second internal vote and no replacement of the player's ruling.</p><div class="callout">The submitted record is fixed in this walkthrough. Cancellation or amendment needs its own declared contract; returning to evidence does not withdraw the action.</div>${evidenceLinks()}<button class="primary" data-go="resolving">Advance the example to resolving Period 3</button>`,
    resolving: () => `<span class="eyebrow">RESOLVING · PERIOD 3</span><h2>The period is resolving.</h2><p class="lead">The submitted choice is fixed. Wait for the authoritative committed observation before presenting completion or granting knowledge.</p><p>${isSpecial() ? "The special practice occupies the one slot; routine work does not run alongside it." : state.routinePaused ? "Standing work was separately paused; Hold adds no special practice." : "Standing work occupies the one slot; Hold adds no special practice."}</p><p class="muted">This static stage represents the wait. It runs no engine, animation timer or hidden weekly step.</p><button class="primary" id="complete">Show the authored completion record</button>`,
    completed: () => `<span class="eyebrow">COMPLETED · PERIOD 3 · AUTHORED FEEDBACK</span><h2>An attempt has results; the situation still needs judgment.</h2><table><thead><tr><th>Separate account</th><th>Visible result in this fixture</th></tr></thead><tbody><tr><td>Material aftermath</td><td>Metal-parts output returns to 960 kg in the maintenance-recovery example. Period 2's 0 kg and lost time remain recorded. Political action is not credited with that recovery; wages and actual shifts remain unmodeled.</td></tr><tr><td>Our enacted practice</td><td>${isSpecial() ? choices[state.ruling].practice : state.routinePaused ? "No practice; standing work was paused separately" : "The previously authorized neighborhood routine"}. ${hours()} organizer-hours used; ${hours() ? 1 : 0} practice slot used.</td></tr><tr><td>Knowledge / relationship</td><td>${state.ruling === "inquiry" ? (state.partner === "limited" ? "An attributed conversation report is available. It describes some workers' experience; it does not disclose everyone's beliefs or prove management's account." : "Our inquiry attempt completed without a partner report. Unknown facts remain unknown; expenditure did not guarantee a knowledge grant.") : state.ruling === "reinforce" ? "Existing workplace tie practice completed in the fixture. No new member, public mandate or numerical solidarity gain is claimed." : "No situation-specific knowledge or workplace-tie effect is credited. Any routine record concerns the neighborhood tie only."}</td></tr><tr><td>Independent partner</td><td>${partnerText()}</td></tr><tr><td>Standing work next</td><td>${routineNext()}. ${state.routinePaused ? "No automatic resume after an explicit Pause." : state.eligible ? "Same scope and 8-hour ceiling for Period 4; one slot only." : "No substitute target or silent escalation. Request review; do not expose hidden reasons."}</td></tr></tbody></table>${evidenceLinks()}<div class="actions"><button class="primary" data-go="appraisal">Appraise and reopen the situation</button></div>`,
    appraisal: () => `<span class="eyebrow">APPRAISAL · REVISED SITUATION</span><h2>Production recovered. What can workers now sustain?</h2><p class="lead">Recovery of a material input does not settle income loss, participation or the organization's direction.</p>${record()}<dl class="facts"><dt>Stated direction</dt><dd>Protect livelihoods and build collective ability to act.</dd><dt>Adopted intention</dt><dd>${choices[state.ruling].title}; chosen by the player.</dd><dt>Enacted practice</dt><dd>${practiceDescription()}. Compare the completion record; intended cooperation and actual participation may differ.</dd><dt>Preserved objection</dt><dd>The workplace contact cautioned that a public promise could exceed workers' available time. No public campaign was authorized by this ruling.</dd><dt>Next situation</dt><dd>Establish remaining income loss and available participation from lawful reports. The partner's limited offer, refusal or silence still matters.</dd><dt>Standing work</dt><dd>${routineNext()} for Period 4.</dd></dl><p>No correctness score, unity reward, compulsory split or automatic learning follows from either output recovery or our chosen practice.</p>${evidenceLinks()}<div class="actions"><button data-go="completed">Return to the completion record</button><button id="compare">Compare another ruling from the same fixture</button></div>`
  };
  $("screen").innerHTML = screens[state.stage]();
}

const evidence = {
  routine: ["Standing-work record · fixture", `<p><span class="pill">PERIOD 1 · COMPLETED EXAMPLE</span></p><p>Our explicitly authorized scope: maintain the existing neighborhood committee tie. Ceiling: 8 organizer-hours; one practice slot.</p><p>Completed contact and received a report. This fictional record demonstrates where attributable routine feedback belongs. No engine receipt or actual knowledge grant exists here.</p><p>The pinned workplace intention remained unexecuted. Routine eligibility, costs and results must come from the same future admission and receipt path as special commitments.</p>`],
  material: ["Workplace and material evidence", `<p><span class="pill">SCENARIO FIXTURE · NOT A QUALIFIED RUNTIME RESULT</span></p><p>The reduced-shift account is an attributed workplace report. The numbers below are a Designed maintenance witness, not proof of the report's cause, actual wages or political readiness.</p><dl class="facts"><dt>Consumer</dt><dd><code>26163-31-33-metal_parts</code></dd><dt>Provider owner</dt><dd><code>owner-26163-81</code></dd><dt>Common opening</dt><dd>Consumer: 2,560 kg metal_stock; 16 batches of initial service.</dd><dt>Service recipe</dt><dd>1 kg spare metal_parts + 10 current person-hours per job; maximum 16 jobs; each job enables one next-period batch.</dd><dt>Comparison</dt><dd>Provider spare stock 256 kg versus 0; employed/reserve 1/0 versus 0/1. All other witness conditions held equal.</dd></dl><table><thead><tr><th>Authored comparison</th><th>Baseline</th><th>Shortage example</th></tr></thead><tbody><tr><td>Period 1 jobs</td><td>16</td><td>0</td></tr><tr><td>Period 2 output</td><td>960 kg</td><td>0 kg</td></tr><tr><td>Period 3 delayed output</td><td>Depends on available inputs</td><td>960 kg recovery prediction</td></tr></tbody></table><p>Finite local replenishment order: 256 kg. Predicted first delivery: 60 kg after maintenance, sharing output with the existing 3,840 kg order. Recovery predictions require execution; staffing retains the maximum of current and prior requests for one period.</p><p><strong>Knowledge boundary:</strong> this authoring comparison is admin/reference evidence. A playable dossier must expose only permitted readings with campaign, period, site, process, good and unit identity. An unavailable reading is not zero. A zero is shown only for a completed reading.</p>`],
  relationship: ["People, commitments and the existing tie", `<p><span class="pill">POLITICAL DESIGN FIXTURES</span></p><dl class="facts"><dt>Workplace committee</dt><dd>Reported fewer shifts in Period 2. Existing admitted relationship is assumed for the Reinforce example; workforce membership and universal support are not inferred.</dd><dt>Our neighborhood contact group</dt><dd>The standing authorization covers 8 hours on the neighborhood tie. An admitted special workplace commitment would replace that routine for one period. Hold continues it unless separately paused.</dd><dt>Independent partner</dt><dd>Response remains unresolved before feedback. Its representative cannot silently commit every member or grant us control of its resources.</dd><dt>Workplace management</dt><dd>Attributes the stoppage to a production constraint. Reported claim, not engine-certified explanation.</dd><dt>Unknown</dt><dd>Private views, absent collective mandates, complete workforce participation and future shift allocation.</dd></dl><p><strong>Reinforce</strong> refers to a bounded practice on an eligible existing relationship, following the planned Organize scope. It is not recruitment. If that relation is unavailable, admission must refuse safely; the interface cannot create it.</p><p>Production dependence is material context. It supplies no solidarity edge or political mandate by itself.</p>`],
  direction: ["Direction and disagreements", `<p><span class="pill">ATTRIBUTED POSITIONS · FICTIONAL WITNESS</span></p><table><thead><tr><th>Known position</th><th>Reason / commitment / limit</th></tr></thead><tbody><tr><td>Workplace contacts favor inquiry</td><td>Workers' experiences may differ. They ask for evidence before a wider promise; their statement is not a workforce mandate.</td></tr><tr><td>Relationship group favors reinforcement</td><td>Existing contact could be harder to sustain during reduced shifts. This commits our practice, not another organization's attendance.</td></tr><tr><td>Neighborhood routine group favors Hold</td><td>Displacement costs a period of its existing work. Waiting leaves the workplace problem unresolved.</td></tr></tbody></table><p>These are proposals about the same decision, not fixed faction slots or support percentages. Support, player authorization, willingness to participate and implementation capacity are separate.</p><p><strong>Final ruling:</strong> the player chooses the organization's eligible response. No subsequent NPC majority substitutes a different line. Normal resource and authority checks remain.</p><p><strong>Independent counterpart:</strong> a fictional employer association could choose reliable staffing or preserve unilateral scheduling. Its own policy would supply its ruling under the same constraints; our choice cannot set it. Its private positions remain unknown unless lawfully reported. This is a design counterpart, not a second implemented simulation.</p>`]
};
document.addEventListener("click", (event) => {
  const button = event.target.closest("button");
  if (!button || button.disabled) return;
  if (button.dataset.go) go(button.dataset.go);
  if (button.dataset.choice) { state.choice = button.dataset.choice; render(); document.querySelector(`[data-choice="${state.choice}"]`).focus(); }
  if (button.dataset.evidence) { const [title, body] = evidence[button.dataset.evidence]; evidenceOpener = button; $("evidence-title").textContent = title; $("evidence-body").innerHTML = body; $("evidence").showModal(); }
  if (button.id === "close-evidence") $("evidence").close();
  if (button.id === "pause-routine") { state.routinePaused = !state.routinePaused; render(); $("pause-routine").focus(); announce(`Standing work ${state.routinePaused ? "paused" : "authorized to resume"} for Period 3; completed records unchanged.`); }
  if (button.id === "submit") {
    if (state.admission === "refused") { $("refusal").textContent = "Not admitted: this commitment is unavailable under the current authorized scope. Draft retained; no practice, expenditure or knowledge grant was recorded. Review your permitted scope before retrying."; announce("Admission refused. Draft preserved; no submitted ruling."); return; }
    state.ruling = state.choice; go("submitted");
  }
  if (button.id === "complete") { state.completed = true; go("completed"); }
  if (button.id === "compare") { state.ruling = null; state.completed = false; go("alternatives"); announce("Returned to the same authored starting conditions; draft retained. This is comparison navigation, not campaign rollback."); }
  if (button.id === "reset") { state = initialState(); go("quiet"); announce("Example restarted. Draft and reviewer settings reset."); }
});
document.addEventListener("input", (event) => { if (event.target.id === "draft-note") state.note = event.target.value; });
document.addEventListener("change", (event) => {
  if (event.target.id === "partner") state.partner = event.target.value;
  if (event.target.id === "eligibility") state.eligible = event.target.value === "eligible";
  if (event.target.id === "admission") state.admission = event.target.value;
});
$("evidence").addEventListener("close", () => { if (evidenceOpener?.isConnected) evidenceOpener.focus(); });
render();
