#!/usr/bin/env python3
"""Canonical DDL extractor for the parquet-canonical reference pipeline (plan
2026-07-19, Task 4).

Extracts every non-internal ``sqlite_master`` object's DDL (tables, indexes,
views — never ``sqlite_%`` bookkeeping objects or NULL-sql auto-indexes) from
a reference DB into ``schema.sql``, in ``sqlite_master`` **rowid order** (the
order objects were created in), then updates the manifest ``schema`` block
via :func:`make_data_artifacts.update_schema_block` — which reads the
manifest first and preserves its ``artifacts`` entries and any existing
``product`` block untouched (the Task 4 atomicity discipline).

Usage::

    uv run python tools/extract_reference_schema.py
    uv run python tools/extract_reference_schema.py --db path/to.sqlite --out schema.sql
"""

from __future__ import annotations

import argparse
import sqlite3
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from make_data_artifacts import (  # noqa: E402
    MANIFEST_PATH,
    ArtifactError,
    _sha256,
    update_schema_block,
)

#: Default source DB — mirrors make_data_artifacts._DEFAULT_DB (kept as its
#: own literal, not a cross-module private import, matching the sibling
#: tools/measure_reference_export.py's DEFAULT_DB precedent).
DEFAULT_DB = Path("data/sqlite/marxist-data-3NF.sqlite")
DEFAULT_OUT = Path("dist/data-artifacts/schema.sql")

HEADER = (
    "-- schema.sql — canonical DDL for the reference DB (parquet-canonical pipeline).\n"
    "-- GENERATED by tools/extract_reference_schema.py — do not edit by hand.\n"
    "-- Statement order = sqlite_master rowid order of the source DB.\n"
)


def extract_schema_sql(conn: sqlite3.Connection) -> str:
    """Extract canonical DDL text for every governed ``sqlite_master``
    object, in rowid order.

    Per-statement canonicalization: strip trailing whitespace per line,
    exactly one trailing ``;``, one blank line between statements, trailing
    newline on the whole file. ``sqlite_%`` internal objects (e.g.
    ``sqlite_sequence``) and NULL-``sql`` rows (auto-indexes from ``UNIQUE``/
    implicit rowid indexes) are excluded — neither is meaningful DDL to
    replay. Objects outside the governed estate (utility bookkeeping like
    ``ingest_checkpoint``, plus their indexes) are excluded by the shared
    ``GOVERNED_PREFIXES`` boundary on ``tbl_name`` — the build product
    contains exactly the governed estate; loaders recreate their own
    bookkeeping DDL on demand via ``metadata.create_all``.

    :param conn: Open connection to the source DB.
    :returns: The full ``schema.sql`` text (header + statements).
    """
    from babylon.sentinels.coverage.catalog import GOVERNED_PREFIXES

    rows = conn.execute(
        "SELECT sql, tbl_name FROM sqlite_master "
        "WHERE sql IS NOT NULL AND name NOT LIKE 'sqlite_%' ORDER BY rowid"
    ).fetchall()
    statements = []
    for sql, tbl_name in rows:
        if not tbl_name.startswith(GOVERNED_PREFIXES):
            continue
        body = "\n".join(line.rstrip() for line in sql.strip().splitlines())
        statements.append(body.rstrip(";") + ";")
    return HEADER + "\n" + "\n\n".join(statements) + "\n"


def schema_census(conn: sqlite3.Connection) -> dict[str, int]:
    """Count governed ``sqlite_master`` objects by type.

    :param conn: Open connection to the source DB.
    :returns: ``{"tables": n, "views": n, "indexes": n}`` — the same
        exclusions as :func:`extract_schema_sql` (``sqlite_%`` objects,
        NULL-``sql`` auto-indexes, and non-governed utility objects never
        count).
    """
    from babylon.sentinels.coverage.catalog import GOVERNED_PREFIXES

    rows = conn.execute(
        "SELECT type, tbl_name FROM sqlite_master "
        "WHERE sql IS NOT NULL AND name NOT LIKE 'sqlite_%'"
    ).fetchall()
    counts: dict[str, int] = {}
    for object_type, tbl_name in rows:
        if not tbl_name.startswith(GOVERNED_PREFIXES):
            continue
        counts[object_type] = counts.get(object_type, 0) + 1
    return {
        "tables": counts.get("table", 0),
        "views": counts.get("view", 0),
        "indexes": counts.get("index", 0),
    }


def main(argv: list[str] | None = None) -> int:
    """Write ``schema.sql`` from ``--db`` and update the manifest ``schema``
    block (preserving ``artifacts`` entries and any ``product`` block)."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--db", type=Path, default=DEFAULT_DB)
    parser.add_argument("--out", type=Path, default=DEFAULT_OUT)
    parser.add_argument(
        "--manifest",
        type=Path,
        default=MANIFEST_PATH,
        help="manifest to update (defaults to data-artifacts.yaml; overridable for tests)",
    )
    args = parser.parse_args(argv)

    if not args.db.exists():
        msg = f"database not found: {args.db}"
        raise ArtifactError(msg)

    conn = sqlite3.connect(f"file:{args.db}?mode=ro", uri=True)
    try:
        text = extract_schema_sql(conn)
        census = schema_census(conn)
    finally:
        conn.close()

    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(text)

    schema_entry: dict[str, object] = {
        "file": str(args.out),
        "sha256": _sha256(args.out),
        **census,
    }
    update_schema_block(args.manifest, schema_entry)
    print(
        f"[schema] wrote {args.out} "
        f"({census['tables']} tables, {census['views']} views, {census['indexes']} indexes)"
    )
    return 0


if __name__ == "__main__":
    try:
        sys.exit(main())
    except ArtifactError as error:
        print(f"[schema] ABORT: {error}", file=sys.stderr)
        sys.exit(2)
