#!/usr/bin/env python3
"""Deterministic PR-body generator — git doctrine §5.9 item 1.

The v2 roadmap draft (``ai/_inbox/archive/tui-roadmap-update.md`` §5.3) says PR
bodies should be *derived* from the commit record, not hand-maintained beside
it: "``train:pr`` generates the task table, baseline claims, and rulings
consumed from ``git log --format='%(trailers)'``". This tool is that
generator, scoped to what item 1 asks for: group conventional commits by
``type(scope)``, surface the declared trailers (``docs/reference/
trailer-schema.rst``), and end with the standard generated-with footer.

It does **not** implement the train-integration machinery (``train:pr``,
reservations, the single-flight lock) — those are items 4-5, explicitly
deferred until the first fan-out plan demands them (roadmap.md §4).

Usage::

    uv run python tools/generate_pr_body.py                       # origin/dev..HEAD
    uv run python tools/generate_pr_body.py --base dev --head HEAD
    mise run pr:body                                               # same, via task

Output is written to stdout by default, or to ``--output PATH``.
"""

from __future__ import annotations

import argparse
import re
import subprocess
import sys
from dataclasses import dataclass
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))

from trailer_schema import (  # type: ignore[import-not-found]  # noqa: E402
    git_log_trailers,
    validate_trailers,
)

#: Canonical conventional-commit types, in the display order this generator
#: uses for grouping (Conventional Commits spec order, then repo-local
#: additions actually seen in this repo's history — ``ci``, ``build``,
#: ``perf``, ``revert`` — with an ``other`` bucket last for anything that
#: doesn't parse as conventional).
TYPE_ORDER: tuple[str, ...] = (
    "feat",
    "fix",
    "refactor",
    "perf",
    "docs",
    "test",
    "build",
    "ci",
    "chore",
    "style",
    "revert",
    "other",
)

_CONVENTIONAL_RE = re.compile(
    r"^(?P<type>[a-z]+)(\((?P<scope>[^)]+)\))?(?P<breaking>!)?: (?P<description>.+)$"
)

# The fixed attribution line every generated body ends with, so a reader can
# tell a generated body from a hand-written one at a glance. Documented as
# canonical in docs/reference/trailer-schema.rst — change both together.
STANDARD_FOOTER = (
    "---\n"
    "*Generated by `tools/generate_pr_body.py` "
    "(git doctrine §5.9 item 1 — trailer schema + generated PR bodies).*"
)


@dataclass(frozen=True)
class Commit:
    """One parsed, non-merge commit in the PR range."""

    sha: str
    subject: str
    type: str
    scope: str | None
    description: str
    trailers: dict[str, str]


def parse_conventional_subject(subject: str) -> tuple[str, str | None, str]:
    """Split a subject line into ``(type, scope, description)``.

    Subjects that don't match the Conventional Commits grammar fall back to
    type ``"other"`` with the full subject as the description, rather than
    raising — a malformed subject is a lint concern (commitizen's job), not
    a reason for this tool to crash mid-generation.
    """
    match = _CONVENTIONAL_RE.match(subject)
    if match is None:
        return "other", None, subject
    commit_type = match.group("type")
    if commit_type not in TYPE_ORDER:
        return "other", None, subject
    return commit_type, match.group("scope"), match.group("description")


def collect_commits(base: str, head: str, repo_root: Path) -> list[Commit]:
    """Collect every non-merge commit in ``base..head``, oldest first.

    Oldest-first (``git log`` naturally returns newest-first; entries are
    reversed here) so the generated body's ordering is a stable function of
    the range's content, not of when the tool happens to run.
    """
    entries = git_log_trailers(f"{base}..{head}", repo_root)
    commits = []
    for sha, subject, trailers in entries:
        commit_type, scope, description = parse_conventional_subject(subject)
        commits.append(Commit(sha, subject, commit_type, scope, description, trailers))
    return list(reversed(commits))


def group_by_type_scope(commits: list[Commit]) -> dict[str, dict[str, list[Commit]]]:
    """Group commits ``{type: {scope: [commits]}}``, scope ``""`` if absent."""
    grouped: dict[str, dict[str, list[Commit]]] = {}
    for commit in commits:
        by_scope = grouped.setdefault(commit.type, {})
        by_scope.setdefault(commit.scope or "", []).append(commit)
    return grouped


def render_commit_sections(commits: list[Commit]) -> str:
    """Render the ``## Commits`` section, grouped by type then scope.

    Type sections appear in ``TYPE_ORDER``; any type outside that tuple
    (should not happen given :func:`parse_conventional_subject`'s fallback,
    but kept defensive) sorts after it alphabetically. Scopes within a type
    are alphabetical; commits within a scope keep collection order (oldest
    first).
    """
    if not commits:
        return "## Commits\n\n_No commits in range._\n"
    grouped = group_by_type_scope(commits)
    ordered_types = [t for t in TYPE_ORDER if t in grouped] + sorted(
        t for t in grouped if t not in TYPE_ORDER
    )
    lines = ["## Commits\n"]
    for commit_type in ordered_types:
        lines.append(f"### {commit_type}\n")
        by_scope = grouped[commit_type]
        for scope in sorted(by_scope):
            for commit in by_scope[scope]:
                prefix = f"**({scope})** " if scope else ""
                lines.append(f"- {prefix}{commit.description} (`{commit.sha[:8]}`)")
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def render_trailers_section(commits: list[Commit]) -> str:
    """Render the ``## Provenance`` section: trailers aggregated across range.

    Each declared trailer key gets the sorted, de-duplicated set of values
    seen across the range's commits — e.g. every distinct ``Task`` id, every
    distinct ``Baselines`` state. A commit missing a trailer simply doesn't
    contribute a value for it; this section reports what *is* declared, it
    does not itself enforce that every commit declares everything (that is
    ``mise run wt:done`` / the ceremony gate's job, not this generator's).
    """
    values: dict[str, set[str]] = {}
    for commit in commits:
        for key, value in commit.trailers.items():
            values.setdefault(key, set()).add(value)
    if not values:
        return "## Provenance\n\n_No structured trailers declared in range._\n"
    lines = ["## Provenance\n"]
    for key in sorted(values):
        joined = ", ".join(f"`{v}`" for v in sorted(values[key]))
        lines.append(f"- **{key}:** {joined}")
    return "\n".join(lines) + "\n"


def render_warnings_section(commits: list[Commit]) -> str:
    """Render a ``## Trailer warnings`` section iff any commit's trailers are
    malformed against ``docs/reference/trailer-schema.rst`` (shape only —
    does not require every schema key be present, since not every commit in
    a range need carry all of them, e.g. a merge-adjacent fixup)."""
    lines: list[str] = []
    for commit in commits:
        if not commit.trailers:
            continue
        for violation in validate_trailers(commit.trailers):
            if violation.startswith("missing required trailer"):
                continue  # absence alone is not a body-generation concern
            lines.append(f"- `{commit.sha[:8]}`: {violation}")
    if not lines:
        return ""
    return "## Trailer warnings\n\n" + "\n".join(lines) + "\n"


def render_pr_body(base: str, head: str, commits: list[Commit]) -> str:
    """Assemble the full deterministic PR body."""
    sections = [
        f"<!-- Generated from {base}..{head} -->",
        render_commit_sections(commits),
        render_trailers_section(commits),
    ]
    warnings = render_warnings_section(commits)
    if warnings:
        sections.append(warnings)
    sections.append(STANDARD_FOOTER)
    return "\n".join(section for section in sections if section) + "\n"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--base", default="origin/dev", help="Base ref (default: origin/dev)")
    parser.add_argument("--head", default="HEAD", help="Head ref (default: HEAD)")
    parser.add_argument("--repo", type=Path, default=Path.cwd(), help="Repository root")
    parser.add_argument("--output", type=Path, help="Write body here instead of stdout")
    args = parser.parse_args(argv)

    try:
        commits = collect_commits(args.base, args.head, args.repo)
    except subprocess.CalledProcessError as exc:
        print(f"generate_pr_body: git failed: {exc.stderr.strip()}", file=sys.stderr)
        return 2

    body = render_pr_body(args.base, args.head, commits)
    if args.output is not None:
        args.output.write_text(body, encoding="utf-8")
    else:
        print(body, end="")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
