#!/usr/bin/env python3
"""Generate the canonical player-editable ``defines.yaml`` from the schema.

``GameDefines`` (the Pydantic schema in :mod:`babylon.config.defines`) is the
single source of truth for every tunable game coefficient. This tool renders
that schema into ``src/babylon/data/defines.yaml`` — the canonical,
player-editable config file (Paradox-style: edit a value, restart, the game
changes; YAML, not INI). ``GameDefines.load_default()`` reads it when present.

Every scalar carries an inline comment with its description and valid range, so
the file is self-documenting — everything a modder needs lives in the one file.

Regenerate after changing a defines default or description::

    poetry run python tools/generate_defines_config.py           # write
    poetry run python tools/generate_defines_config.py --check    # CI: verify in sync

Safety: the generated YAML is verified to round-trip
(``GameDefines.load_from_yaml(out) == GameDefines()``) before it is written, so
a formatting bug can never ship a canonical file that changes the game.

See Also:
    :mod:`babylon.config.defines` — the schema this tool renders.
    ``docs/how-to/modding-defines.rst`` — the player-facing modding guide.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path
from typing import Any

import annotated_types as at
import yaml
from pydantic import BaseModel

sys.path.insert(0, str(Path(__file__).parent.parent / "src"))

from babylon.config.defines import GameDefines  # noqa: E402

_REPO_ROOT = Path(__file__).parent.parent
_YAML_PATH = _REPO_ROOT / "src" / "babylon" / "data" / "defines.yaml"

_YAML_HEADER = """\
# =====================================================================
# Babylon — Canonical Game Configuration (defines.yaml)
# =====================================================================
#
# This is THE single source of truth for every tunable game coefficient.
# It is the player-moddable config file: change a value below, restart the
# simulation, and the game behaves differently — the way Paradox grand-strategy
# games expose their rules (but YAML, not INI).
#
# HOW TO MOD:
#   1. Edit any value below. Keep the YAML structure, key names, and value types
#      intact — the inline comment on each line gives its meaning and valid range.
#   2. Restart the simulation. `GameDefines.load_default()` reads this file
#      (src/babylon/data/defines.yaml) and applies your values.
#   3. To revert to the shipped defaults, delete this file OR regenerate it:
#        poetry run python tools/generate_defines_config.py
#
# NOTES:
#   * This file is GENERATED from the `GameDefines` Pydantic schema. Do not add
#     new keys by hand — add the field to the schema and regenerate. Hand-edited
#     VALUES are honored; hand-added structure may be ignored by the loader.
#   * A category omitted here falls back to its schema defaults; a value omitted
#     within a present category falls back to that field's default.
#   * See docs/how-to/modding-defines.rst for the full modding guide.
#
# Generated by tools/generate_defines_config.py — do not edit the structure by hand.
# =====================================================================
"""


def _category_doc(model_cls: type[BaseModel]) -> str:
    """First non-empty line of a category model's docstring (or empty)."""
    doc = (model_cls.__doc__ or "").strip()
    return doc.splitlines()[0].strip() if doc else ""


def _submodel_of(annotation: Any) -> type[BaseModel] | None:
    """Return the BaseModel subclass an annotation refers to, else None."""
    if isinstance(annotation, type) and issubclass(annotation, BaseModel):
        return annotation
    return None


def _scalar_to_yaml(value: Any) -> str:
    """Render a scalar as its inline YAML form (first emitted line)."""
    return yaml.safe_dump(value, default_flow_style=True, allow_unicode=True).splitlines()[0]


def _constraint_text(field: Any) -> str:
    """Human-readable ``(>= 0, <= 1)``-style range from a FieldInfo's metadata."""
    parts: list[str] = []
    for meta in getattr(field, "metadata", []):
        if isinstance(meta, at.Ge):
            parts.append(f">= {meta.ge}")
        elif isinstance(meta, at.Le):
            parts.append(f"<= {meta.le}")
        elif isinstance(meta, at.Gt):
            parts.append(f"> {meta.gt}")
        elif isinstance(meta, at.Lt):
            parts.append(f"< {meta.lt}")
        elif isinstance(meta, at.MultipleOf):
            parts.append(f"x{meta.multiple_of}")
    return ", ".join(parts)


def _comment_for(field: Any) -> str:
    """Build the inline ``# description (range)`` comment for a scalar field."""
    if field is None:
        return ""
    desc = (field.description or "").replace("\n", " ").strip()
    rng = _constraint_text(field)
    if desc and rng:
        return f"  # {desc} ({rng})"
    if desc:
        return f"  # {desc}"
    if rng:
        return f"  # ({rng})"
    return ""


def _emit_mapping(
    data: dict[str, Any],
    model_cls: type[BaseModel] | None,
    indent: str,
) -> list[str]:
    """Recursively emit a dict as commented YAML lines.

    Scalars get an inline ``# description (range)`` from the field metadata.
    Nested defines models recurse (comments preserved). Free-form dict/list
    fields are emitted via ``yaml.safe_dump`` (round-trip faithful) with only a
    key-level comment.
    """
    lines: list[str] = []
    fields = model_cls.model_fields if model_cls is not None else {}

    for key, value in data.items():
        field = fields.get(key)
        submodel = _submodel_of(field.annotation) if field is not None else None

        if isinstance(value, dict) and submodel is not None:
            desc = (field.description or "").strip() if field is not None else ""
            lines.append(f"{indent}{key}:" + (f"  # {desc}" if desc else ""))
            lines.extend(_emit_mapping(value, submodel, indent + "  "))
        elif isinstance(value, (dict, list)):
            desc = (field.description or "").strip() if field is not None else ""
            comment = f"  # {desc}" if desc else ""
            block = yaml.safe_dump(
                {key: value}, default_flow_style=False, sort_keys=False, allow_unicode=True
            ).rstrip("\n")
            block_lines = block.splitlines()
            lines.append(f"{indent}{block_lines[0]}{comment}")
            lines.extend(f"{indent}{ln}" for ln in block_lines[1:])
        else:
            lines.append(f"{indent}{key}: {_scalar_to_yaml(value)}{_comment_for(field)}")

    return lines


def build_yaml(base: GameDefines) -> str:
    """Build the full commented ``defines.yaml`` text from GameDefines."""
    dump = base.model_dump(mode="json")
    out: list[str] = [_YAML_HEADER]

    for name, field in GameDefines.model_fields.items():
        submodel = _submodel_of(field.annotation)
        doc = _category_doc(submodel) if submodel is not None else ""
        out.append("")
        out.append("# " + "-" * 69)
        out.append(f"# {name}" + (f" — {doc}" if doc else ""))
        out.append("# " + "-" * 69)
        out.append(f"{name}:")
        out.extend(_emit_mapping(dump[name], submodel, "  "))

    return "\n".join(out) + "\n"


def main() -> int:
    """Generate defines.yaml, verifying round-trip first.

    With ``--check``, generate in memory and compare against the on-disk file
    WITHOUT writing; exit non-zero if it is stale (schema changed but the file
    was not regenerated). This is the CI/guard mode.
    """
    parser = argparse.ArgumentParser(description="Generate the canonical defines.yaml")
    parser.add_argument(
        "--check",
        action="store_true",
        help="Verify the on-disk defines.yaml is up to date without writing (exit 1 if stale).",
    )
    args = parser.parse_args()

    base = GameDefines()
    yaml_text = build_yaml(base)

    # HARD SAFETY GATE: the generated YAML must reconstruct GameDefines() exactly.
    reloaded = GameDefines._from_yaml_dict(yaml.safe_load(yaml_text))
    if reloaded != base:
        print("ERROR: generated YAML does NOT round-trip to GameDefines().", file=sys.stderr)
        for cat in GameDefines.model_fields:
            if getattr(reloaded, cat) != getattr(base, cat):
                print(f"  mismatched category: {cat}", file=sys.stderr)
        return 1

    if args.check:
        if not _YAML_PATH.exists() or _YAML_PATH.read_text(encoding="utf-8") != yaml_text:
            print(
                "STALE: src/babylon/data/defines.yaml is out of date. Regenerate with:\n"
                "  poetry run python tools/generate_defines_config.py",
                file=sys.stderr,
            )
            return 1
        print("defines.yaml is up to date.")
        return 0

    _YAML_PATH.parent.mkdir(parents=True, exist_ok=True)
    _YAML_PATH.write_text(yaml_text, encoding="utf-8")
    print(f"Wrote {_YAML_PATH.relative_to(_REPO_ROOT)} ({len(yaml_text.splitlines())} lines)")

    # Confirm the on-disk file also round-trips (belt and suspenders).
    if GameDefines.load_from_yaml(_YAML_PATH) != base:
        print("ERROR: on-disk defines.yaml does not round-trip.", file=sys.stderr)
        return 1
    print("Round-trip verified: load_from_yaml(defines.yaml) == GameDefines().")
    return 0


if __name__ == "__main__":
    sys.exit(main())
