//! Explicit current source disposition and strict singular-envelope admission.
use super::{FoundationContentBundle, FoundationSources};
use crate::RustPersistenceRuntimeError;

const DOMAIN: &[u8] = b"babylon.campaign-foundation-content.v3\0";
const MAX_BYTES: usize = 67_108_864;
const MAX_SOURCE: usize = 1_048_576;
const H3_DOMAIN: &[u8] = b"babylon.h3.reference-bundle-composite.v1\0";

/// The current source that reconstructs the opening graph.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
#[repr(u8)]
pub enum FoundationContentKind {
    AuthoredBscn = 1,
    /// Captured sources regenerated by the pinned current economic compiler.
    EconomicCatalog = 2,
}

/// Exact source-framing refusals, independent of database or replay failures.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum FoundationContentError {
    Bound,
    Truncated,
    Domain,
    Version,
    Kind,
    FieldOrder,
    OptionTag,
    Utf8,
    EmbeddedNul,
    Trailing,
    Noncanonical,
}
impl std::fmt::Display for FoundationContentError {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(formatter, "foundation content refused: {self:?}")
    }
}
impl std::error::Error for FoundationContentError {}

impl From<FoundationContentError> for RustPersistenceRuntimeError {
    fn from(value: FoundationContentError) -> Self {
        Self::FoundationContent(value)
    }
}

impl FoundationContentBundle {
    /// Decode the singular current source blob, with no legacy format fallback.
    /// # Errors
    /// Refuses invalid framing, source bounds, source semantics or changed bytes.
    pub fn decode(bytes: &[u8]) -> Result<Self, RustPersistenceRuntimeError> {
        let mut cursor = Cursor::new(bytes)?;
        if cursor.take(DOMAIN.len())? != DOMAIN {
            return Err(FoundationContentError::Domain.into());
        }
        if cursor.word()? != 3 {
            return Err(FoundationContentError::Version.into());
        }
        let bundle = match cursor.byte()? {
            1 => Self::decode_authored(&mut cursor)?,
            2 => {
                cursor.tag(1)?;
                let raw = cursor.blob(MAX_BYTES)?;
                let catalog = crate::economic_catalog::CapturedEconomicCatalog::decode(
                    raw,
                    babylon_kernel::content_digest::sha256_of(raw),
                )
                .map_err(RustPersistenceRuntimeError::EconomicCatalog)?;
                Self::from_economic_catalog(catalog)?
            }
            _ => return Err(FoundationContentError::Kind.into()),
        };
        if !cursor.remaining.is_empty() {
            return Err(FoundationContentError::Trailing.into());
        }
        if bundle.canonical_bytes() != bytes {
            return Err(FoundationContentError::Noncanonical.into());
        }
        Ok(bundle)
    }
    fn decode_authored(cursor: &mut Cursor<'_>) -> Result<Self, RustPersistenceRuntimeError> {
        cursor.tag(1)?;
        let scenario = cursor.source()?;
        cursor.tag(2)?;
        let prelude = match cursor.byte()? {
            0 => None,
            1 => Some(cursor.source()?),
            _ => return Err(FoundationContentError::OptionTag.into()),
        };
        cursor.tag(3)?;
        let rules = cursor.source()?;
        cursor.tag(4)?;
        let defines = cursor.blob(MAX_BYTES)?;
        cursor.tag(5)?;
        let reference = cursor.blob(MAX_BYTES)?;
        Self::try_new(scenario, prelude, rules, defines, reference)
    }

    /// Capture the sole source table, consuming the already admitted opening.
    /// # Errors
    /// Refuses invalid rules or an envelope exceeding the complete byte bound.
    pub fn from_economic_catalog(
        catalog: crate::economic_catalog::CapturedEconomicCatalog,
    ) -> Result<Self, RustPersistenceRuntimeError> {
        use babylon_bsl::{canonical_ast::rules_hash_of, rule_pipeline::split_content};
        use babylon_kernel::{content_digest::ContentDigest, tick_content_hash::RefDigest};
        let rules = catalog
            .source_text(crate::economic_catalog::SourceArtifactKind::Rules)
            .map_err(RustPersistenceRuntimeError::EconomicCatalog)?;
        let (_, rules) =
            split_content(rules).map_err(|_| RustPersistenceRuntimeError::ReplaySource)?;
        let rules = rules.into_iter().map(|rule| rule.form).collect::<Vec<_>>();
        let content_digest = ContentDigest {
            defines_hash: catalog.digest(),
            rules_hash: rules_hash_of(&rules)
                .map_err(|_| RustPersistenceRuntimeError::ReplaySource)?,
        };
        let reference_digest = RefDigest::from_bytes(catalog.digest());
        let count = catalog.canonical_bytes().len();
        if count
            .checked_add(DOMAIN.len() + 10)
            .is_none_or(|length| length > MAX_BYTES)
        {
            return Err(FoundationContentError::Bound.into());
        }
        let mut canonical_bytes = Vec::with_capacity(DOMAIN.len() + 10 + count);
        canonical_bytes.extend_from_slice(DOMAIN);
        canonical_bytes.extend_from_slice(&3_u32.to_be_bytes());
        canonical_bytes.push(FoundationContentKind::EconomicCatalog as u8);
        canonical_bytes.push(1);
        canonical_bytes.extend_from_slice(
            &u32::try_from(count)
                .map_err(|_| FoundationContentError::Bound)?
                .to_be_bytes(),
        );
        canonical_bytes.extend_from_slice(catalog.canonical_bytes());
        Ok(Self {
            sources: FoundationSources::Economic(Box::new(catalog)),
            content_digest,
            reference_digest,
            canonical_bytes,
        })
    }
    /// Borrow the already admitted source-derived opening without regeneration.
    #[must_use]
    pub fn economic_catalog(&self) -> Option<&crate::economic_catalog::CapturedEconomicCatalog> {
        match &self.sources {
            FoundationSources::Economic(catalog) => Some(catalog),
            FoundationSources::Authored(_) => None,
        }
    }

    pub(crate) fn territory_county_map(
        &self,
    ) -> Result<Vec<crate::territory_county_map::TerritoryCountyMapRow>, RustPersistenceRuntimeError>
    {
        if let Some(catalog) = self.economic_catalog() {
            return catalog
                .county_map()
                .map_err(RustPersistenceRuntimeError::EconomicCatalog);
        }
        let scenario = std::str::from_utf8(self.scenario_source_bytes())
            .map_err(|_| FoundationContentError::Utf8)?;
        let prelude = self
            .prelude_source_bytes()
            .map(std::str::from_utf8)
            .transpose()
            .map_err(|_| FoundationContentError::Utf8)?;
        crate::territory_county_map::extract_declared_territory_county_map(scenario, prelude)
            .map_err(RustPersistenceRuntimeError::TerritoryCountyMap)
    }

    pub(crate) fn geographic_binding(
        &self,
    ) -> Result<(&'static str, Option<[u8; 32]>), RustPersistenceRuntimeError> {
        if let Some(catalog) = self.economic_catalog() {
            return Ok(catalog.geographic_binding());
        }
        let bytes = self.reference_bundle_manifest_bytes();
        if bytes.len() != H3_DOMAIN.len() + 64 || !bytes.starts_with(H3_DOMAIN) {
            return Err(RustPersistenceRuntimeError::ReplaySource);
        }
        let digest = bytes[H3_DOMAIN.len()..H3_DOMAIN.len() + 32]
            .try_into()
            .map_err(|_| RustPersistenceRuntimeError::ReplaySource)?;
        Ok(("michigan-control", Some(digest)))
    }

    /// Return the explicit reconstruction source disposition.
    #[must_use]
    pub const fn kind(&self) -> FoundationContentKind {
        match &self.sources {
            FoundationSources::Authored(_) => FoundationContentKind::AuthoredBscn,
            FoundationSources::Economic(_) => FoundationContentKind::EconomicCatalog,
        }
    }
}

struct Cursor<'a> {
    remaining: &'a [u8],
}
impl<'a> Cursor<'a> {
    fn new(bytes: &'a [u8]) -> Result<Self, FoundationContentError> {
        if bytes.len() > MAX_BYTES {
            return Err(FoundationContentError::Bound);
        }
        Ok(Self { remaining: bytes })
    }
    fn take(&mut self, length: usize) -> Result<&'a [u8], FoundationContentError> {
        let value = self
            .remaining
            .get(..length)
            .ok_or(FoundationContentError::Truncated)?;
        self.remaining = &self.remaining[length..];
        Ok(value)
    }
    fn byte(&mut self) -> Result<u8, FoundationContentError> {
        Ok(self.take(1)?[0])
    }
    fn word(&mut self) -> Result<u32, FoundationContentError> {
        let bytes = self
            .take(4)?
            .try_into()
            .map_err(|_| FoundationContentError::Truncated)?;
        Ok(u32::from_be_bytes(bytes))
    }
    fn tag(&mut self, expected: u8) -> Result<(), FoundationContentError> {
        if self.byte()? != expected {
            return Err(FoundationContentError::FieldOrder);
        }
        Ok(())
    }
    fn blob(&mut self, maximum: usize) -> Result<&'a [u8], FoundationContentError> {
        let length = usize::try_from(self.word()?).map_err(|_| FoundationContentError::Bound)?;
        if length > maximum {
            return Err(FoundationContentError::Bound);
        }
        self.take(length)
    }
    fn source(&mut self) -> Result<&'a str, FoundationContentError> {
        let bytes = self.blob(MAX_SOURCE)?;
        if bytes.contains(&0) {
            return Err(FoundationContentError::EmbeddedNul);
        }
        std::str::from_utf8(bytes).map_err(|_| FoundationContentError::Utf8)
    }
}
